### ISSUE TITLE
Request: Add `isMaximized` and `isMinimized`

### ISSUE THREAD

**Issue by zyrouge** [leanflutter/window_manager#1]

**Comment by lijy91** [comment]
`isMaximized` has added to `linux`, `macOS`, `windows`.
`isMinimized ` has added to `macOS`, `windows`.

I haven’t found how to minimize it in linux, because `gtk_window_minimize`, `gtk_window_unminimize` only exists in gtk4.

**Comment by zyrouge** [comment]
This can be closed I guess?

**Comment by lijy91** [comment]
I created a new issue to follow it up.

https://github.com/leanflutter/window_manager/issues/2
