### ISSUE TITLE
能否对标题栏的背景颜色和图标进行设置呢？

### ISSUE THREAD

**Issue by LuyueWang** [leanflutter/window_manager#102]
我想对标题栏的背景颜色（或者设置模糊效果？）或图标进行个性化设置，但没有找到相关设置

**Comment by lijy91** [comment]
是指默认的标题栏还是自定义的标题栏？

**Comment by LuyueWang** [comment]
系统默认的标题栏，显示最小化最大化关闭那栏

**Comment by lijy91** [comment]
暂时不支持，目前没计划支持，你可以使用 WindowCaption 来自定义
