### ISSUE TITLE
[Windows]setAlignment(Alignment.bottomRight) 软件底部被任务栏遮挡

### ISSUE THREAD

**Issue by j787701730** [leanflutter/window_manager#112]
![image](https://user-images.githubusercontent.com/23625690/161356180-0750e917-3611-4ede-8589-847b42870bce.png)
上面的Alignment.bottomRight被任务栏遮挡部分. 
![image](https://user-images.githubusercontent.com/23625690/161356198-c3a5b00e-b903-4bf9-b788-70678fb20bfa.png)

**Comment by lijy91** [comment]
Fixed, please update to `v0.2.1`.

**Comment by j787701730** [comment]
感谢修复
