### ISSUE TITLE
[Linux] Add an option to remove window shadows

### ISSUE THREAD

**Issue by scotch-hub** [leanflutter/window_manager#118]
Is there any way this is possible?
I'm trying to create custom bottom rounded corners and the shadows are getting in the way.

![Screenshot from 2022-04-08 12-37-06](https://user-images.githubusercontent.com/73116038/162421120-4c0e7bab-32c2-4813-82ee-eb524911ba79.png)

**Comment by lijy91** [comment]
You can call SetAsFrameless to remove borders and shadows

**Comment by lijy91** [comment]
There are also DragToMoveArea and DragToResizeArea widgets for moving and resizing.
