### ISSUE TITLE
Improve Documentation?

### ISSUE THREAD

**Issue by damywise** [leanflutter/window_manager#120]
Every once in a while, we get a question like
- How do I move the window?
- How can I make the window frameless?
- How do I style the window?
- How can I hide the caption/title bar?
- How do I use the `startResize()` method?
- etc.

I think the documentation needs to be improved.
Please do suggest.

**Comment by lijy91** [comment]
I made a website https://leanflutter.org , I will add more documentation and examples to this website

https://github.com/leanflutter/website
