### ISSUE TITLE
MacOs the button on window bar is Visible

### ISSUE THREAD

**Issue by nio74** [leanflutter/window_manager#121]
Good day I have try your example in Macos  bat the button left is visible. It's possible Resolve?
![Schermata 2022-04-11 alle 13 51 03](https://user-images.githubusercontent.com/15077816/162734026-70ee48bb-217b-44cc-aa85-2ceabe140a92.png)
.

**Comment by lijy91** [comment]
Please set `windowButtonVisibility` to false.

```dart
windowManager.setTitleBarStyle(TitleBarStyle.hidden, windowButtonVisibility: false);
```
