### ISSUE TITLE
How to disable the Maximize Button?

### ISSUE THREAD

**Issue by NuclearGear** [leanflutter/window_manager#127]
I want to disable the maximize button.
Has there any function to implement that?
Thanks.

**Comment by lijy91** [comment]
Not yet supported, will be supported in the future.

https://github.com/electron/electron/blob/9d4aceb94045cc6ff292904a1c46f3d3a09a5d55/shell/browser/native_window_mac.mm#L836
https://github.com/electron/electron/blob/9d4aceb94045cc6ff292904a1c46f3d3a09a5d55/shell/browser/native_window_views.cc#L891

**Comment by NuclearGear** [comment]
Got it!
Thanks!
