### ISSUE TITLE
await windowManager.ensureInitialized() causes error?

### ISSUE THREAD

**Issue by mjacobsca** [leanflutter/window_manager#130]
Hello all,

My main.dart looks like this:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Must add this line.
  await windowManager.ensureInitialized();

  runApp(const MyApp());
}
```

HOWEVER, windowManager.ensureInitialized() causes an error at run time on the Android Simulator, but not when building for a Windows app. The error text is as follows:

MissingPluginException (MissingPluginException(No implementation found for method ensureInitialized on channel window_manager))

**Comment by lijy91** [comment]
Please don't use it on non-desktop platforms

```dart
bool get kIsLinux => !kIsWeb && Platform.isLinux;
bool get kIsMacOS => !kIsWeb && Platform.isMacOS;
bool get kIsWindows => !kIsWeb && Platform.isWindows;

if (kIsLinux || kIsMacOS || kIsWindows) {
  await windowManager.ensureInitialized();
}
```
