### ISSUE TITLE
window overflow

### ISSUE THREAD

**Issue by zezo357** [leanflutter/window_manager#131]
calling 

```
      windowManager.setFullScreen(true);
```
      
      
then going back to normal callling 
```
  windowManager.setFullScreen(false);
      windowManager.restore();
```

cases window to go out of boundry in the bottom part 

normal view 
![image](https://user-images.githubusercontent.com/25157308/165002732-534bf7c5-f882-4935-956b-421d0e1543d6.png)

after calling the commands
![image](https://user-images.githubusercontent.com/25157308/165002753-c5e7eeb2-465c-4213-bf8b-b149e5970c4d.png)

using window_manager 0.2.2

and it was happening on 0.2.1 too

**Comment by lijy91** [comment]
restore only works to restore the state before minimize.

**Comment by zezo357** [comment]
> restore only works to restore the state before minimize.

i am sorry but can you provide an example ?

like what should be done to get the correct window (without overflow)

**Comment by zezo357** [comment]
also calling ` windowManager.setFullScreen(false);`
without restore

gives the same effect 
window is back to normal size but there still the overflow

**Comment by krida2000** [comment]
Same problem. I fixed it by changing window size on 1 pixel after `windowManager.setFullScreen(false);`.

**Comment by damywise** [comment]
I have found a solution for this, but I haven't made a PR.
You can check it [here](https://github.com/leanflutter/window_manager/commit/13094153bfa6841eb90bef671d98f0678c806c9a) and [here](https://github.com/leanflutter/window_manager/commit/9a0d681a94eb4206aea48878c9aa4fd90a8c4748).

**Comment by damywise** [comment]
When going back from full screen to normal size, the bottom part of the app is cropped. My guess is the size of the Flutter View and the app (frame) wasn't synced or something like that. To fix this, I made a method inside Windows that forces redrawing the entire app by increasing window size by 1 pixel in and then reduces it by 1 pixel.

**Comment by zezo357** [comment]
> Same problem. I fixed it by changing window size on 1 pixel after `windowManager.setFullScreen(false);`.

i am sorry but ,how can i do that with window manger package?

**Comment by zezo357** [comment]
i did it like this
```
await windowManager.setFullScreen(state);
Size size = await windowManager.getSize();
await windowManager.setSize(Size(size.width + 1, size.height + 1));
```

**Comment by fufesou** [comment]
@damywise @lijy91 Hi, I've check the code. The latest commit does not call `ForceRefresh()`, and `ForceChildRefresh()` will not be called in https://github.com/leanflutter/window_manager/blob/73c39f406c56de682b6c34d8cc744cecdcb471bb/windows/window_manager_plugin.cpp#L294

Is this still an issue, or Windows changed something to fix this?

@krida2000 @abdelaziz-mahdy We also put a fix with `await windowManager.setSize(Size(size.width + 1, size.height + 1));`. But it causes another issue that window is changed after exiting fullscreen. Why not call `await windowManager.setSize(Size(size.width, size.height));` after that?

**Comment by damywise** [comment]
Heya @fufesou I've forgotten about it, sorry. I don't know why or when it's gone. It's been a while since I've developed Windows app with such features.
