### ISSUE TITLE
Some window events are not emmited when bitsdojo_window is present in the project

### ISSUE THREAD

**Issue by jakub-stefaniak** [leanflutter/window_manager#134]
I encountered a strange bug. Some window events are not emmited when bitsdojo_window is present in the project. 

I noticed that the onWindowMinimized method is not being invoked. After some digging i removed bitsdojo_window plugin and it started to work again.

Just in case, if someone is also stuck with that problem - just remove bitsdojo.

**Comment by lijy91** [comment]
Thanks for the reminder, please don't use two window management plugins at the same time.
