### ISSUE TITLE
🐛 minimize/maximize buttons react kinda slow

### ISSUE THREAD

**Issue by bdlukaa** [leanflutter/window_manager#136]
I noticed that the "windows" buttons (minimize, maximize, close) seem to react kinda slow. It looks like there is a pause of approx. 1 second before the action is performed. Why is that?

_originally filed by @[solaristhesun](https://github.com/solaristhesun) on https://github.com/bdlukaa/fluent_ui/issues/305_

**Comment by damywise** [comment]
The answer to #135 and #136 is actually the same. Both are caused by [this line](https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/main.dart#L162). You should not wrap WindowCaption with DragToMoveArea. WindowCaption already has DragToMoveArea widget beside the buttons.

**Comment by bdlukaa** [comment]
@damywise thanks for the reply. I will try and LYK

**Comment by bdlukaa** [comment]
Indeed! Thanks for the feedback
