### ISSUE TITLE
setBackgroundColor supports Windows7

### ISSUE THREAD

**Issue by jkouubb** [leanflutter/window_manager#140]
I am trying to make a floating-ball on Windows. Since it is round, I have to make win32 window background transparent. 
window_manager does have a function named "setBackgroundColor", which invokes "SetWindowCompositionAttribute" to do the job.
However, SetWindowCompositionAttribute does not work on Windows7, so "setBackgroundColor" actually does not sopport Windows7.
Will you please improve this method?

**Comment by lijy91** [comment]
No plan to support windows 7, feel free to submit PR if someone can implement it
