### ISSUE TITLE
Proposal: system menu

### ISSUE THREAD

**Issue by jpnurmi** [leanflutter/window_manager#141]
Could there be API to show the window system menu on Linux and Windows?
- https://docs.gtk.org/gdk3/method.Window.show_window_menu.html
- https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmenu

![image](https://user-images.githubusercontent.com/140617/166916830-214761c7-6971-437d-804f-c039bd9da38c.png)

**Comment by lijy91** [comment]
I tried adding this functionality for the windows platform, but it doesn't seem to display the state of the menu items correctly

**Comment by jpnurmi** [comment]
Strange, the docs claim that it should be automatically taken care of. Which state is wrong?

> The system automatically grays items on the standard window menu, depending on the situation. The application can perform its own checking or graying by responding to the [WM_INITMENU](https://docs.microsoft.com/en-us/windows/desktop/menurc/wm-initmenu) message that is sent before any menu is displayed.

**Comment by lijy91** [comment]
I've added a popUpWindowMenu method for windows and linux platforms, but I can't fix this incorrect state on Windows for now.

**Comment by jpnurmi** [comment]
Interesting, the warnings were actually from the X11 backend because VS Code sets GDK_BACKEND=x11. The Wayland backend would crash due to missing device, but both are fixed by https://github.com/leanflutter/window_manager/pull/145.
