### ISSUE TITLE
Set size while keeping window centered

### ISSUE THREAD

**Issue by chimon2000** [leanflutter/window_manager#142]
Currently, the window grows downward and to the right, causing it to lose its positioning.

It would be nice to be able to set the size of the application window while keeping the window centered in the same call.

**Comment by lijy91** [comment]
We have a `setBounds` method that can set both position and size,  You can use the [screen_retriever](https://github.com/leanflutter/screen_retriever) plugin to get the screen size and then calculate the correct new position

```dart
Rect bounds = Rect.fromLTWH(10, 10, 800, 600);
windowManager.setBounds(bounds);
```

**Comment by chimon2000** [comment]
@lijy91  `setBounds` currently ignores the `animate` property.

https://github.com/leanflutter/window_manager/blob/c243222532618b231872b8e3a2b6378ffd5d22bd/lib/src/window_manager.dart#L270-L274

**Comment by lijy91** [comment]
> @lijy91 `setBounds` currently ignores the `animate` property.

i will fix it
