### ISSUE TITLE
How to prohibit maximize window by double clicking toolbar or area within "DragToMoveArea"?

### ISSUE THREAD

**Issue by dbsxdbsx** [leanflutter/window_manager#143]
version :  window_manager: ^0.2.2 on win10

I want to prevent user to resize app, my main code like this :
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Platform.isWindows) {
    await WindowManager.instance.ensureInitialized();
    windowManager.waitUntilReadyToShow().then((_) async {
      await windowManager.setTitleBarStyle(
        TitleBarStyle.hidden,
        windowButtonVisibility: false,
      );
      await windowManager.setSize(const Size(755, 545));
      await windowManager.setMinimumSize(const Size(755, 545));
      await windowManager.setPreventClose(true);
      await windowManager.setSkipTaskbar(false);
      await windowManager.setResizable(false);
      await windowManager.setMinimizable(true);
      await windowManager.center();
      await windowManager.focus();
      await windowManager.show();
    });
  }
...
```
And my home page is  wrapped within "DragToMoveArea". But the app can still be maximized by double clicking any area of the page.
By the way, as there is `setMinimizable`, why there is no `setMaximizable`?

**Comment by lijy91** [comment]
You can do without the DragToMoveArea widget, it's essentially a GestureDetector. 

```dart
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.translucent,
      onPanStart: (details) {
        windowManager.startDragging();
      },
      onDoubleTap: () async {
        // bool isMaximized = await windowManager.isMaximized();
        // if (!isMaximized) {
        //   windowManager.maximize();
        // } else {
        //  windowManager.unmaximize();
        // }
      },
      child: child,
    );
  }
```

**Comment by dbsxdbsx** [comment]
> ```dart
>   return GestureDetector(
>       behavior: HitTestBehavior.translucent,
>       onPanStart: (details) {
>         windowManager.startDragging();
>       },
>       onDoubleTap: () async {
>         // bool isMaximized = await windowManager.isMaximized();
>         // if (!isMaximized) {
>         //   windowManager.maximize();
>         // } else {
>         //  windowManager.unmaximize();
>         // }
>       },
>       child: child,
>     );
> ```

But when dragging, the mouse icon would be duplicated.

**Comment by lijy91** [comment]
> > ```dart
> >   return GestureDetector(
> >       behavior: HitTestBehavior.translucent,
> >       onPanStart: (details) {
> >         windowManager.startDragging();
> >       },
> >       onDoubleTap: () async {
> >         // bool isMaximized = await windowManager.isMaximized();
> >         // if (!isMaximized) {
> >         //   windowManager.maximize();
> >         // } else {
> >         //  windowManager.unmaximize();
> >         // }
> >       },
> >       child: child,
> >     );
> > ```
> 
> But when dragging, the mouse icon would be duplicated.

I don't understand what you mean, do you have a screenshot?

**Comment by dbsxdbsx** [comment]
> > > ```dart
> > >   return GestureDetector(
> > >       behavior: HitTestBehavior.translucent,
> > >       onPanStart: (details) {
> > >         windowManager.startDragging();
> > >       },
> > >       onDoubleTap: () async {
> > >         // bool isMaximized = await windowManager.isMaximized();
> > >         // if (!isMaximized) {
> > >         //   windowManager.maximize();
> > >         // } else {
> > >         //  windowManager.unmaximize();
> > >         // }
> > >       },
> > >       child: child,
> > >     );
> > > ```
> > 
> > 
> > But when dragging, the mouse icon would be duplicated.
> 
> I don't understand what you mean, do you have a screenshot?

It is strange that this phenomena disappeared today.
