### ISSUE TITLE
[MacOS] windowManager.hide() kills the flutter app

### ISSUE THREAD

**Issue by mdudzinski** [leanflutter/window_manager#15]
First - thanks for all the packages that improve flutter desktop experience, they are essential for building apps that integrate with the desktop OSes. Great job.

I've been trying to build a flutter app that can be shown/hidden using a system-wide hotkey using this package and https://github.com/leanflutter/hotkey_manager.

I created a default flutter app with `flutter create`, enabled MacOS support and added `window_manager: ^0.0.5` + `  hotkey_manager: ^0.1.4` as dependencies.
Next, I changed the `main()` method to look like this https://pastebin.com/wGNinbzW.

When I hit `alt + q` the app is shown and I can interact with the UI. After I hit the hotkey again, the app is hidden but I no longer can show it again with the same key combination. 
When running in debug mode, the following is returned in the console:
```
Launching lib/main.dart on macOS in debug mode...
lib/main.dart:1
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:023A239B-6591-577A-8E58-6FA382A6710C }
{ platform:macOS, name:Any Mac }
Connecting to VM Service at ws://127.0.0.1:50391/GHnaYaoFjW0=/ws
Lost connection to device.
Exited (sigterm)
```

When the app is launched with `flutter run -d macos --release`, no errors are shown but I cannot find the app process with `ps`.

**Comment by lijy91** [comment]
You should call ensureInitialized before calling any method

```diff
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Must add this line.
+  await windowManager.ensureInitialized();

  windowManager.waitUntilReadyToShow().then((_) async {
-    await windowManager.ensureInitialized();
    await windowManager.setAsFrameless();
    await windowManager.setSize(const Size(600, 300));
    await windowManager.setPosition(const Offset(300, 300));
    await windowManager.setResizable(false);
    await windowManager.setSkipTaskbar(true);
    await windowManager.setAlwaysOnTop(true);
  });
 
-  WidgetsFlutterBinding.ensureInitialized();
  // For hot reload, `unregisterAll()` needs to be called.
  hotKeyManager.unregisterAll();
 
  HotKey _hotKey = HotKey(
    KeyCode.keyQ,
    modifiers: [KeyModifier.alt],
  );
 
  await hotKeyManager.register(
    _hotKey,
    keyUpHandler: (hotKey) async {
      if (await windowManager.isVisible()) {
        windowManager.hide();
      } else {
        windowManager.show();
      }
    },
  );
  runApp(const MyApp());
}
```

**Comment by mdudzinski** [comment]
Not sure why I put `windowManager.ensureInitialized()` in the `then` block and I wasn't aware of `applicationShouldTerminateAfterLastWindowClosed` in Cocoa. Now it works like a charm, thank you!

**Comment by lijy91** [comment]
I missed this part of the guide, now it has been added to the README.md
