### ISSUE TITLE
setAspectRatio crashes on macOS 

### ISSUE THREAD

**Issue by TadashiCZ** [leanflutter/window_manager#150]
The error is:
`window_manager/WindowManager.swift:44: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

The main method is:
`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  windowManager.setAspectRatio(16/9);
  runApp(const MyApp());
}`

**Comment by lijy91** [comment]
Have you tried running the example and testing this functionality?

**Comment by lijy91** [comment]
I think you should call it after waitUntilReadyToShow callback.

```dart
windowManager.waitUntilReadyToShow(windowOptions, () async {
  windowManager.setAspectRatio(16/9);
});
```
