### ISSUE TITLE
无法和flutter_native_view（dart_vlc）一起使用

### ISSUE THREAD

**Issue by yhsj0919** [leanflutter/window_manager#152]
当设置  window_class, title.c_str(), WS_OVERLAPPEDWINDOW,后，程序正常构建然后闪退，
不删除 WS_VISIBLE 没问题

**Comment by j787701730** [comment]
我也碰到了. setPreventClose(true), 在flutter_native_view页面, 关闭按钮调用windowManager.hide(), 窗口直接卡死. 暂时改用windowManager.minimize();
