### ISSUE TITLE
listen to changes from isAlwaysOnTop

### ISSUE THREAD

**Issue by smedasn** [leanflutter/window_manager#154]
is there any way to detect when the state of this changes?
for example when another application also sets its state to setAlwaysOnTop

**Comment by damywise** [comment]
On Windows, when multiple applications are set to always on top, they won't affect each other. Both will be topmost simultaneously. At least that's what I get from my test.

**Comment by lijy91** [comment]
I don't think this is necessary. The system allows multiple applications to set AlwaysOnTop. I think it may be necessary to listen to the blur event and do something when the window is focused.
