### ISSUE TITLE
Hide window title bar

### ISSUE THREAD

**Issue by thegrxp** [leanflutter/window_manager#16]
Is it possible to resize a frameless window or to hide the title bar of the window?
I would like to add my own design of the action buttons (minimize, maximize, close). 
I've managed to do it on MacOS using Xcode but I struggle to do it on Windows.

Thank you for this amazing lib!

**Comment by dodatw** [comment]
I also need this feature, I need "No Caption Bar", and resizable.

**Comment by lijy91** [comment]
windows and macos is Support `setTitleBarStyle` method.

**Comment by lijy91** [comment]
Follow up on https://github.com/leanflutter/window_manager/issues/38
