### ISSUE TITLE
 Unhandled Exception: MissingPluginException(No implementation found for method getBounds on channel window_manager)

### ISSUE THREAD

**Issue by jonahzheng** [leanflutter/window_manager#160]
Size size = await windowManager.getSize();
windowManager.setSize(Size(size.width + 100, size.height + 100),);

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method getBounds on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      WindowManager.getBounds (package:window_manager/src/window_manager.dart:288:46)
<asynchronous suspension>
#2      WindowManager.getSize (package:window_manager/src/window_manager.dart:321:19)
<asynchronous suspension>
#3      main.<anonymous closure> (package:test/main.dart:35:19)
<asynchronous suspension>
```

**Comment by damywise** [comment]
> `No implementation found for method getBounds on channel window_manager`

[This commit](https://github.com/leanflutter/window_manager/commit/75ae9d1596c4ca29a7e48dadd10a0abb33b1c92f) breaks the `getBounds` method for Windows.

**Comment by lijy91** [comment]
I finished implementing the native getBounds/setBounds methods.

https://github.com/leanflutter/window_manager/commit/fd678fed8816ad7cbb7425fcbc0dc7a8d88afd9c
