### ISSUE TITLE
setTitlebarColor & setTitlebarTextColor

### ISSUE THREAD

**Issue by ollyde** [leanflutter/window_manager#162]
This package would be perfect if we could setTitlebarColor & setTitlebarTextColor :-D

**Comment by ollydixon** [comment]
@lijy91 at the moment on Windows setTitleBarStyle on windows crashes the app, fyi. (Windows 11)

**Comment by lijy91** [comment]
> setTitleBarStyle crashes windows on launch though, would be nice to just set the color :-D

Can you provide some logs or reproducing code?

**Comment by ollydixon** [comment]
@lijy91 it's the same as the sample but you add setTitleBarStyle none.

```
import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Must add this line.
  await windowManager.ensureInitialized();

  WindowOptions windowOptions = WindowOptions(
  );
  // This is actually wrong in the docs, you need to put await before it otherwise on release it will break.
  // Probably a race condition.
  await windowManager.waitUntilReadyToShow(windowOptions, () async {
  });

  // This crashes on Windows 11. Not possible to change color on title bar with this library :-/
  setTitleBarStyle(TitleBarStyle.hidden)

  runApp(MyApp());
}
```

**Comment by lijy91** [comment]
You set the `titleBarStyle` in the callback of waitUntilReadyToShow
```dart
windowManager.waitUntilReadyToShow(windowOptions, () async {
  setTitleBarStyle(TitleBarStyle.hidden);
});
```

**Comment by ollydixon** [comment]
@lijy91 we tried that, and we tried in the options as well. On Windows 11 it crashes.

**Comment by damywise** [comment]
Have you tried the example app? Does it also crash?

**Comment by ollydixon** [comment]
@lijy91 @damywise I gave an example of it crashing on Windows 11.```setTitleBarStyle(TitleBarStyle.hidden);```

I can try run the sample app tonight, maybe there is a conflicting package or something.

**Comment by ollydixon** [comment]
Running the sample app it crashes, can you reopen this? 

```
    await windowManager.ensureInitialized();
    await windowManager.waitUntilReadyToShow(
      WindowOptions(
        title: "Bap",
        titleBarStyle: (isMacOS || isWindows) ? TitleBarStyle.hidden : TitleBarStyle.normal,
      ),
      () async {},
    );
```

**Comment by ollydixon** [comment]
It works if I do the following though. @lijy91 

`Future.delayed(Duration(seconds: 2)).then((value) => windowManager.setTitleBarStyle(TitleBarStyle.hidden));}`
