### ISSUE TITLE
[windows] window overflow [#131]  too in window_manager: ^0.2.5

### ISSUE THREAD

**Issue by j787701730** [leanflutter/window_manager#170]
window overflow #131

I use window_manager: ^0.2.5
```
 Flutter (Channel stable, 3.0.2, on Microsoft Windows [版本 10.0.19044.1766], locale zh-CN)
    • Flutter version 3.0.2 at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2
```

![微信截图_20220622110448](https://user-images.githubusercontent.com/23625690/174936274-8e3f2cf7-6d94-4f7b-9e02-501008babd6b.png)

windowManager.setFullScreen(false);
![微信截图_20220622110514](https://user-images.githubusercontent.com/23625690/174936297-9e419e71-2d1a-4865-bb0d-c5551c4a646f.png)

**Comment by zezo357** [comment]
anyfix?

**Comment by lijy91** [comment]
Please update to 0.3.5

**Comment by rustdesk** [comment]
3.5 does not work on windows7,  https://github.com/rustdesk/rustdesk/discussions/4819
I downgraded to 3.4, now working on windows7

**Comment by damywise** [comment]
Maybe make a new issue?
I don't see how it is related to this.
