### ISSUE TITLE
setIgnoreMouseEvents: MissingPluginException

### ISSUE THREAD

**Issue by lynxcode42** [leanflutter/window_manager#176]
Hello and thank you for the plugin.
I was looking for a way to annotate screencasts on linux desktops.
Stumbled on window_manager with "_setIgnoreMouseEvents_" and opacity feature.
Saw your nice [demo on twitter](https://twitter.com/lijy91/status/1502115704677433353).
But somehow I can't get the bundled demo example working properly.

**error message**:
----------------------------------------
>: window_manager/example$ flutter run -d linux
```
ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method setIgnoreMouseEvents on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165)
<asynchronous suspension>
#1      WindowManager.setIgnoreMouseEvents (package:window_manager/src/window_manager.dart:578)
<asynchronous suspension>
#2      _HomePageState._buildBody.<anonymous closure> (package:window_manager_example/pages/home.dart:794)
<asynchronous suspension>
```
**window_manager** : v0.2.5
----------------------------------------
**flutter --version**
----------------------------------------
```
Flutter 3.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 676cefaaff (8 days ago) • 2022-06-22 11:34:49   ##-0700
Engine • revision ffe7b86a1e
Tools • Dart 2.17.5 • DevTools 2.12.2
```
**Desktop**: Kubuntu 22.04
----------------------------------------
```
OS: Kubuntu 22.04 LTS x86_64
Kernel: 5.15.0-25-generic 
DE: Plasma 5.24.4 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Terminal: konsole
```

**Comment by lynxcode42** [comment]
vscode screenshot
----------------------------------------
![window_manager_#176](https://user-images.githubusercontent.com/108466872/176684685-6f5aff65-8c9c-4410-ae13-83e17d7443fa.png)

**Comment by lynxcode42** [comment]
Just tried on Win11: it works flawlessly. On Manjaro.KDE it also fails the same way like on Kubuntu. So it is maybe KDE at fault here?
.
**Win11 screenshot**
____________________
![window_manager_win11](https://user-images.githubusercontent.com/108466872/176739767-3b2bc4bb-a1aa-4663-8ea2-902f37895347.png)

**Comment by lijy91** [comment]
Sorry, the setIgnoreMouseEvents method is not yet supported on the linux platform

**Comment by lynxcode42** [comment]
That's unfortunate. Thank you for the feedback. I'll check the **_CHANGELOG.md_** from time to time to see if this feature is implemented for Linux desktops.

I'm closing this issue.
![setIgnoreMouseEvents_win_mac_only](https://user-images.githubusercontent.com/108466872/176883710-734ac6f2-d41f-41e4-8f8b-97fe7c6f939b.png)
