### ISSUE TITLE
cannot create sub window

### ISSUE THREAD

**Issue by ghrejoe** [leanflutter/window_manager#177]

**Comment by sanihaq** [comment]
same issue
> [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method createSubWindow on channel window_manager)

**Comment by tenraneko** [comment]
Same
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method createSubWindow on channel window_manager)

[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22000.1335], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.17)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.74.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by lijy91** [comment]
The createSubWindow method has been removed, the current implementation has too many issues.
