### ISSUE TITLE
right bound overlapped after leaving fullscreen

### ISSUE THREAD

**Issue by kevinxxq** [leanflutter/window_manager#181]
Hi great Team,
thank you for the package to solve many windows headache.

I found one issue, you may reproduce it through following steps:
1. official example.
2. set the normal title bar(not frameless)
3. change the window size to medium(not max)
4. set fullscreen, then set it back.

You will see the right bound is not coming back correctly:
![e537d164b858a732c2d65473b132b96](https://user-images.githubusercontent.com/55800697/178649939-0bc0895c-fc09-4174-8b5e-cc148eadba52.png)

Thank you.

**Comment by lijy91** [comment]
This issue has been fixed, please update to 0.3.5 https://github.com/leanflutter/window_manager/pull/359
