### ISSUE TITLE
Any chance of multi window support?

### ISSUE THREAD

**Issue by tyrel2000** [leanflutter/window_manager#183]
I think this package is awesome, and works really well for my desktop usage when I have a single window.
I'm also using a package to support [multiple Flutter windows on the desktop](https://pub.dev/packages/desktop_multi_window), but the packages don't play nicely together (I'm guessing it's something to do with using the correct window handles in the background). I'm using this for a Windows desktop app.

Is there any chance these packages could work together, or else look at adding support to the window_manager package to handle multiple windows too?

**Comment by damywise** [comment]
Seems like [RustDesk](https://github.com/rustdesk/rustdesk) is trying to do exactly that https://github.com/Kingtous/rustdesk_desktop_multi_window.

**Comment by lijy91** [comment]
I temporarily gave up the multi-window attempt and look forward to the official flutter effort.
