### ISSUE TITLE
[LINUX] No way to start resize when title is hidden

### ISSUE THREAD

**Issue by prateekmedia** [leanflutter/window_manager#188]
On Linux there is no room for resizing whereas same app when using bitsdojo_window can be resized easily as there is a mouse pointer when getting near window end.

**Comment by damywise** [comment]
https://github.com/leanflutter/window_manager/blob/d7a66d80b96563961c03bd2c939b27afe1cc0f50/lib/src/widgets/drag_to_resize_area.dart

**Comment by prateekmedia** [comment]
Thanks!
