### ISSUE TITLE
windowManager.setSkipTaskbar(true) seems to cause the app to quit on Windows

### ISSUE THREAD

**Issue by quinn** [leanflutter/window_manager#190]
no log output that I can see, just exits with `Lost connection to device.` in the terminal.

**Comment by damywise** [comment]
Did you try this on the example app?

**Comment by quinn** [comment]
no, i'll give that a try now, thank you

**Comment by quinn** [comment]
Ok, I added it to the example and it works (no item in the taskbar)

https://github.com/quinn/window_manager/commit/f3fee11badfd5e47aff32deee14f4ef833c46aae

**Comment by quinn** [comment]
ok, i was able to fix in my app by moving it inside of:
```
windowManager.waitUntilReadyToShow(
```

**Comment by hpelitebook745G2** [comment]
thanks @quinn for the tip!
this works for me:
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await windowManager.ensureInitialized();

  windowManager.waitUntilReadyToShow().then((_) async {
    await windowManager.setSkipTaskbar(false);
  });
}
```
