### ISSUE TITLE
setSize but to the left and top

### ISSUE THREAD

**Issue by damywise** [leanflutter/window_manager#20]
The current setSize resizes only to the right and bottom direction, so I'm asking if it is possible or is there a plan for a setSize that resizes to the left and/or to the top direction?

**Comment by lijy91** [comment]
You need to calculate the new position and modify it, the current default coordinate starting point is topLeft

**Comment by damywise** [comment]
Does that mean I have to setPosition after setSize so the window moves according to the size change?

**Comment by lijy91** [comment]
Yes, you can use the `setBounds` method

**Comment by damywise** [comment]
Hmm when I use setBounds to resize to the left or bottom it jitters so much.
Doesn't happen when I resize to the right or bottom though.

**Comment by damywise** [comment]
Example: this video

https://user-images.githubusercontent.com/25608913/143370561-14d772b0-b303-4652-acdc-ad6391577e37.mp4

**Comment by lijy91** [comment]
Is it running on windows?

**Comment by damywise** [comment]
Yep

**Comment by lijy91** [comment]
It seems to be a problem with the engine, resize will cause the canvas to stretch

**Comment by damywise** [comment]
Guess I just need to wait for a fix in Flutter itself then.
