### ISSUE TITLE
Remove Window Border/Outline

### ISSUE THREAD

**Issue by wachidsusilo** [leanflutter/window_manager#201]
I'm creating app for windows. Is it possible to remove window black border/outline?

![Screenshot 2022-08-17 124622](https://user-images.githubusercontent.com/50637964/185044111-dc4d2098-103e-40ea-adac-139461770335.png)

**Comment by ksm-android** [comment]
+1

**Comment by chouchoudhunter** [comment]
same problem

**Comment by pangujs** [comment]
+1

**Comment by naychrist** [comment]
+1 for osx and windows

I need to create an app that spans multiple monitors and appears full screen. I can set the OSX menu bar to auto hide, set window pos to top left and width and height to span all monitors etc but the only thing remaining is the rounded corners and 1 pixel border. I saw that the old desktop_window package has some unexposed border functions for this that might be useful: https://github.com/mix1009/desktop_window/blob/master/macos/Classes/DesktopWindowPlugin.swift

**Comment by naychrist** [comment]
does `setAsFrameless()` close this?

**Comment by 214zzl995** [comment]
can add the following code in main.cpp
`LONG lStyle = ::GetWindowLong(window.GetHandle(), GWL_STYLE); 
lStyle &= ~(WS_CAPTION | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX | WS_SYSMENU);
::SetWindowLongPtr(window.GetHandle(), GWL_STYLE, lStyle);`

**Comment by xSILENCEx** [comment]
```dart
await windowManager.setAsFrameless();
```

**Comment by lijy91** [comment]
> ```dart
> await windowManager.setAsFrameless();
> ```

This is correct
