### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by NetComTech** [leanflutter/window_manager#202]
E/flutter ( 5090): #0      User.fromSnap
package:connect/models/user.dart:40
E/flutter ( 5090): #1      AuthMethods.getUserDetails
package:connect/resources/auth_methods.dart:18
E/flutter ( 5090): <asynchronous suspension>
E/flutter ( 5090): #2      UserProvider.refreshUser
package:connect/providers/user_provider.dart:12
E/flutter ( 5090): <asynchronous suspension>
E/flutter ( 5090): #3      _ResponsiveLayoutState.addData
package:connect/responsive/responsive_layout_screen.dart:28
E/flutter ( 5090): <asynchronous suspension>
E/flutter ( 5090):

Please I need help to solve this problem

**Comment by lijy91** [comment]
This doesn't look like the problem is caused by window_manager
