### ISSUE TITLE
setMinimizable not working on windows 10

### ISSUE THREAD

**Issue by SeifElmotaz** [leanflutter/window_manager#21]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setMinimizable on channel window_manager)
`

Hi i tryed to use `setMinimizable(false)` but it gives me this error and it's not working I tried to run `flutter clean` and run the app again but nothing happens.

**Comment by lijy91** [comment]
This method will be released in the next version

**Comment by SeifElmotaz** [comment]
Ok thanks. I will wait.
Thanks for this amazing plugins.
