### ISSUE TITLE
[macOS] windowManager.hide() closes the application

### ISSUE THREAD

**Issue by alessiogaldy** [leanflutter/window_manager#214]
Invoking `windowManager.hide()` on macOS closes the application instead of just hiding the window.
This seems to be happening when calling `orderOut(nil)` here:
https://github.com/leanflutter/window_manager/blob/651c76ce6e249de231ae925b978a5d9384804220/macos/Classes/WindowManager.swift#L115
Replacing this with `NSApp.hide(nil);` seems to fix the issue.

**Comment by romannep** [comment]
Same issue.

@alessiogaldy can you create PR?

**Comment by d1y** [comment]
alter `/macos/Runner/AppDelegate.swift`

```diff
import Cocoa
import FlutterMacOS

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
-    return true
+    return false
  }
}
```

**Comment by alessiogaldy** [comment]
@d1y that worked, thank you!
