### ISSUE TITLE
Can't set a custom Icon for WindowCaptionButton

### ISSUE THREAD

**Issue by WinXaito** [leanflutter/window_manager#216]
This parameter is never used: https://github.com/leanflutter/window_manager/blob/main/lib/src/widgets/window_caption_button.dart#L30

And if iconName is null, we throw an error: https://github.com/leanflutter/window_manager/blob/main/lib/src/widgets/window_caption_button.dart#L174

I want to add custom button with custom icon, like this:

![image](https://user-images.githubusercontent.com/8223773/188454072-cac605ac-4cbf-401d-b529-262743927943.png)

And if we give a Widget, le color can't be changed on hover, so I propose something like that:

Add a parameter `iconData` instead `icon` of type `IconData`, and do something like that

```dart
widget.iconData != null
? Icon(
    color: iconColor,
    widget.iconData,
    size: 16,
  )
: WindowCaptionButtonIcon(
    name: widget.iconName!,
    color: iconColor,
  ),
```

Edit: and add a verification like this `assert(iconData != null || iconName != null)`

**Comment by lijy91** [comment]
This widget will be a separate package in a future version. Now, you can copy the code of this widget to your project for customization.
