### ISSUE TITLE
setAlwaysOnBottom will support Windows in the future?

### ISSUE THREAD

**Issue by j787701730** [leanflutter/window_manager#224]

**Comment by j787701730** [comment]
[https://zhuanlan.zhihu.com/p/37877070 ](https://zhuanlan.zhihu.com/p/37877070 ) 效果像这种的. Linux setAlwaysOnBottom 是这种效果? 还是我理解错了.

**Comment by temzints** [comment]
Any updates on this?

Found this on [https://stackoverflow.com/questions/527950/how-to-make-always-on-bottom-window](stackoverflow)

**Comment by lijy91** [comment]
Version 0.3.2 supported
