### ISSUE TITLE
Some useful functions.

### ISSUE THREAD

**Issue by dodatw** [leanflutter/window_manager#23]
It is a very useful widget and let my app better.
I have some suggestions for it
1. remove standard Windows/macOS/Linux title bar and buttons
2. Hide window on startup
3. consider scaleFactor

I found https://pub.dev/packages/bitsdojo_window support these functions. 
But the owner did not update for more than 6 months.

**Comment by lijy91** [comment]
I am trying to add these features, but it still has some problems.

https://github.com/leanflutter/window_manager/commit/36a0409def884b377782ad2d9ec009ed2e35d932

**Comment by lijy91** [comment]
Follow up on https://github.com/leanflutter/window_manager/issues/38 https://github.com/leanflutter/window_manager/issues/39
