### ISSUE TITLE
Fatal error: Unable to bridge NSNumber to Float

### ISSUE THREAD

**Issue by LastMonopoly** [leanflutter/window_manager#235]
windowManager.setPosition(Offset(x, y)) won't work when either x or y is Float.

**Comment by LastMonopoly** [comment]
Steps to reproduce:

change related code in /example/lib/pages/home.dart to the following

CupertinoButton(
    child: Text('x+20'),
    onPressed: () async {
      Offset p = await windowManager.getPosition();
      windowManager.setPosition(Offset(p.dx + 20.1, p.dy));
      setState(() {});
    },
  ),
  CupertinoButton(
    child: Text('x-20'),
    onPressed: () async {
      Offset p = await windowManager.getPosition();
      windowManager.setPosition(Offset(p.dx - 20.2, p.dy));
      setState(() {});
    },
  ),
  CupertinoButton(
    child: Text('y+20'),
    onPressed: () async {
      Offset p = await windowManager.getPosition();
      windowManager.setPosition(Offset(p.dx, p.dy + 20.3));
      setState(() {});
    },
  ),
  CupertinoButton(
    child: Text('y-20'),
    onPressed: () async {
      Offset p = await windowManager.getPosition();
      windowManager.setPosition(Offset(p.dx, p.dy - 20.4));
      setState(() {});
    },
  ),

**Comment by lijy91** [comment]
Fixed, please update to 0.2.8
