### ISSUE TITLE
error G5ACFE20E: Required named parameter 'child' must be provided.

### ISSUE THREAD

**Issue by El-GeorgesW** [leanflutter/window_manager#243]
After updating to 0.2.7 i get this error :

error G5ACFE20E: Required named parameter 'child' must be provided.

Even when i try to build window_manager/example

**Comment by damywise** [comment]
Can you give full output?

**Comment by El-GeorgesW** [comment]
**My Flutter app output**

/C:/Users/georg/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/window_manager-0.2.7/lib/src/widgets/virtu
al_window_frame.dart:149:30: Error: Required named parameter 'child' must be provided.
    return VirtualWindowFrame(
                             ^
/C:/Users/georg/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/window_manager-0.2.7/lib/src/widgets/virtu
al_window_frame.dart:20:9: Context: Found this candidate, but the arguments don't match.
  const VirtualWindowFrame({
        ^^^^^^^^^^^^^^^^^^
Performing hot restart...                                               
Restarted application in 14,739ms.
Try again after fixing the above error(s).

**window_manager/example output**

PS C:\Users\georg\Shared\wm_example> flutter pub get
Running "flutter pub get" in wm_example...                               8.4s
Resolving dependencies...
+ async 2.9.0 (2.10.0 available)
+ boolean_selector 2.1.0 (2.1.1 available)
+ bot_toast 4.0.3
+ characters 1.2.1
+ clock 1.1.1
+ collection 1.16.0 (1.17.0 available)
+ cupertino_icons 1.0.5
+ fake_async 1.3.1
+ flutter 0.0.0 from sdk flutter
+ flutter_test 0.0.0 from sdk flutter
+ js 0.6.4 (0.6.5 available)
+ matcher 0.12.12 (0.12.13 available)
+ material_color_utilities 0.2.0
+ menu_base 0.1.1
+ meta 1.8.0
+ path 1.8.2
+ preference_list 0.0.1
+ screen_retriever 0.1.4
+ shortid 0.1.2
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.9.1
+ stack_trace 1.10.0 (1.11.0 available)
+ stream_channel 2.1.1
+ string_scanner 1.1.1 (1.2.0 available)
+ term_glyph 1.2.1
+ test_api 0.4.14 (0.4.16 available)
+ tray_manager 0.1.9 (0.2.0 available)
+ vector_math 2.1.4
+ window_manager 0.2.7
Downloading tray_manager 0.1.9...
Downloading screen_retriever 0.1.4...
Changed 29 dependencies!
PS C:\Users\georg\Shared\wm_example> flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/window_manager-0.2.7/lib/src/widgets/virtual_window_frame.dart(149,30): error G5ACFE20E: Required named parameter 'child' must be provided. [C:\Users\georg\Shared\wm_example\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\georg\Shared\wm_example\build\windows\CMakeFiles\737b4d7e22564f3b3a458843f57bdb9a\flutter_windows.dll.rule;C:\Users\georg\Shared\wm_example\build\windows\CMakeFiles\4f479edc6d556cc7bc1feb92e2f0bca2\flutter_assemble.rule' exited with code 1. [C:\Users\georg\Shared\wm_example\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...                                         
Exception: Build process failed.

**Comment by El-GeorgesW** [comment]
> Can you give full output?

**My Flutter app output**

/C:/Users/georg/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/window_manager-0.2.7/lib/src/widgets/virtu
al_window_frame.dart:149:30: Error: Required named parameter 'child' must be provided.
    return VirtualWindowFrame(
                             ^
/C:/Users/georg/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/window_manager-0.2.7/lib/src/widgets/virtu
al_window_frame.dart:20:9: Context: Found this candidate, but the arguments don't match.
  const VirtualWindowFrame({
        ^^^^^^^^^^^^^^^^^^
Performing hot restart...                                               
Restarted application in 14,739ms.
Try again after fixing the above error(s).

**window_manager/example output**

PS C:\Users\georg\Shared\wm_example> flutter pub get
Running "flutter pub get" in wm_example...                               8.4s
Resolving dependencies...
+ async 2.9.0 (2.10.0 available)
+ boolean_selector 2.1.0 (2.1.1 available)
+ bot_toast 4.0.3
+ characters 1.2.1
+ clock 1.1.1
+ collection 1.16.0 (1.17.0 available)
+ cupertino_icons 1.0.5
+ fake_async 1.3.1
+ flutter 0.0.0 from sdk flutter
+ flutter_test 0.0.0 from sdk flutter
+ js 0.6.4 (0.6.5 available)
+ matcher 0.12.12 (0.12.13 available)
+ material_color_utilities 0.2.0
+ menu_base 0.1.1
+ meta 1.8.0
+ path 1.8.2
+ preference_list 0.0.1
+ screen_retriever 0.1.4
+ shortid 0.1.2
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.9.1
+ stack_trace 1.10.0 (1.11.0 available)
+ stream_channel 2.1.1
+ string_scanner 1.1.1 (1.2.0 available)
+ term_glyph 1.2.1
+ test_api 0.4.14 (0.4.16 available)
+ tray_manager 0.1.9 (0.2.0 available)
+ vector_math 2.1.4
+ window_manager 0.2.7
Downloading tray_manager 0.1.9...
Downloading screen_retriever 0.1.4...
Changed 29 dependencies!
PS C:\Users\georg\Shared\wm_example> flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/window_manager-0.2.7/lib/src/widgets/virtual_window_frame.dart(149,30): error G5ACFE20E: Required named parameter 'child' must be provided. [C:\Users\georg\Shared\wm_example\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\georg\Shared\wm_example\build\windows\CMakeFiles\737b4d7e22564f3b3a458843f57bdb9a\flutter_windows.dll.rule;C:\Users\georg\Shared\wm_example\build\windows\CMakeFiles\4f479edc6d556cc7bc1feb92e2f0bca2\flutter_assemble.rule' exited with code 1. [C:\Users\georg\Shared\wm_example\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...                                         
Exception: Build process failed.

**Comment by lijy91** [comment]
Can you provide the information output by flutter doctor?

**Comment by lijy91** [comment]
Please upgrade your Flutter to 3.7.10 and try again. If the problem persists, open it again
