### ISSUE TITLE
Getting the initial "blink" when having set custom window size, app title

### ISSUE THREAD

**Issue by john-rager** [leanflutter/window_manager#247]
Great package, but running into issue after having set custom window size.

I followed the getting started instructions and used this code in main():
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await windowManager.ensureInitialized();

  WindowOptions windowOptions = const WindowOptions(
    size: Size(1500, 1000),
    center: true,
    backgroundColor: Colors.transparent,
    skipTaskbar: false,
    title: '[Application Name]',
  );
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });

  runApp(const MyApp());
}
```

When I run my app in Windows, I see an initial blank window with the size, location, and title specified in the default ...runner/main.cpp, then after a second or so it resizes, repositions, and shows the window with my custom title.  This is distracting to users.  I've seen from reading around that this is a common issue with Flutter apps because it starts to render the window before running anything else, but I also saw some posts claiming that window_manager has solved this,

Am I doing something wrong/missing something, or will my only option be to edit main.cpp?

Thanks!

**Comment by damywise** [comment]
https://github.com/leanflutter/window_manager#windows
This is the only way to do it as far as I know.

**Comment by john-rager** [comment]
@damywise thank you!  I had seen that section of the docs but didn't realize it deals with this issue.
