### ISSUE TITLE
How to use window_manager in a cross-platform application

### ISSUE THREAD

**Issue by gaddlord** [leanflutter/window_manager#251]
I am building a cross platform application for both Web, Mac, Linux, Windows, Android and iOS.

window_manager works great on Windows. But once I run the app as Chrome web application it crashes with:

![image](https://user-images.githubusercontent.com/279005/206437470-c32b538b-6196-45d3-ab17-ed65942d5325.png)

I don't need the window_manager features for web but don't know how to conditionally disable it in the cross-platform codebase.

Please advice.

**Comment by jpnurmi** [comment]
Use the [`kIsWeb`](https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html) top-level constant from `flutter/foundation.dart`.
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:window_manager/window_manager.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  if (!kIsWeb) {
    windowManager.ensureInitialized();
  }

  runApp(...);
}
```

**Comment by jpnurmi** [comment]
@lijy91 Do you think it would make sense to have `WindowManager.ensureInitialized()` return a boolean indicating whether `window_manager` is available on that platform? This could be one option to eliminate the `kIsWeb` check that is currently necessary for any app that wants to support Web.

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (!kIsWeb) {
    await windowManager.ensureInitialized();
    await windowManager.setTitleBarStyle(TitleBarStyle.hidden);
  }

  runApp(MyApp());
}
```
vs.
```dart
import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (await windowManager.ensureInitialized()) {
    await windowManager.setTitleBarStyle(TitleBarStyle.hidden);
  }

  runApp(MyApp());
}
```

**Comment by gaddlord** [comment]
Worked for me with if (!kIsWeb) { ... }
