### ISSUE TITLE
The WindowCaptionButtonIcon's icon appears to be flawed

### ISSUE THREAD

**Issue by KasumiNova** [leanflutter/window_manager#262]
I noticed some blurring of the icons in the window buttons in the title bar, which affected the look and feel.

- Icons in system windows (in Windows 11)
![image](https://user-images.githubusercontent.com/48862050/207949428-96260872-2a81-4c06-8256-f783df4bc8a7.png)
- Icons in Flutter (using WindowCaption in window_manager)
![image](https://user-images.githubusercontent.com/48862050/207949567-86f239a8-f4a8-4096-8efa-13fd7c0263ec.png)

If you look closely at it, you will see that WindowCation using window_manager is much more blurry than the icons in the system, and the icons in the system are relatively clear (because the screenshot are compressed, it may be difficult to see the difference, you can compare these icons in your windows).

Is there a solution for this?

**Comment by kolyneh** [comment]
Since `WindowCaption` isn't a native window button, there will be differrence between them.
You can try to remove the WindowCaption then use the native buttons instead:
```dart
/// Set up window brightness base on your theme mode.
await WindowManager.instance.setBrightness(Brightness.light);
await WindowManager.instance.setTitleBarStyle(TitleBarStyle.normal);
```

**Comment by damywise** [comment]
Yeah the scale of the widgets is not that accurate iirc. You can copy code of the widgets and adjust them to the correct scale.
