### ISSUE TITLE
ability to know some action ended

### ISSUE THREAD

**Issue by sleepreading** [leanflutter/window_manager#28]
Sorry, my English skill is no good...
Currently, we don't know when the user operation ended:
If provide some extra parameters, it would be very helpful:
```
// when resizing the window, we will receive a bunch of resizing-message, but can't determine the last one(mouse left click up)
void onWindowResize(int state) {
  ....
}
void onWindowMove(int state) {
}
```

**Comment by lijy91** [comment]
The `resized` and `moved` events should be supported on `macos` and `windows` in the future

**Comment by lijy91** [comment]
可以添加我的微信 `lijy91` 加入 LeanFlutter 讨论组

**Comment by sleepreading** [comment]
> The `resized` and `moved` events should be supported on `macos` and `windows` in the future

That would be Great!

**Comment by lijy91** [comment]
Supported, will be released in the next version. (linux is not supported)

```dart
  /// Emitted once when the window has finished being resized.
  ///
  /// @platforms macos,windows
  void onWindowResized() {}

  /// Emitted once when the window is moved to a new position.
  ///
  /// @platforms macos,windows
  void onWindowMoved() {}
```
