### ISSUE TITLE
Resize Linux Window without VirtualWindow

### ISSUE THREAD

**Issue by jr1221** [leanflutter/window_manager#288]
Hello,

Is it possible to make the window resizable in Linux without creating a VirtualWindowFrame?  Or at least hide the frame?

I tried `setAsFrameless()` and `setBackgroundColor(Colors.transparent)` but they both left a black border around my app when using `VirtualWindowFrame`.  However, on Windows, I do not need the frame to get a resizable app.  I am using the example app.  Any help would be appreciated.

(ref from mjansen4857/pathplanner#226)

**Comment by anilgupta83** [comment]
+1

**Comment by lijy91** [comment]
Please update to 0.3.2, fixed by https://github.com/leanflutter/window_manager/pull/318
