### ISSUE TITLE
macOS Window transparency broken in Flutter 3.7.0

### ISSUE THREAD

**Issue by elincoln** [leanflutter/window_manager#293]
Flutter version: 3.7.0 
App type: Material
OS: macOS 12.6.1

Issue:
Setting `WindowOptions.backgroundColor` and `Scaffold.backgroundColor` to `Colors.transparent` or any color with an alpha-value < 255 ignores the alpha value and just draws a fully opaque window.

However, this works correctly when using Flutter 3.3.10 with a MaterialApp. 

Notes:
I dug in the Swift/macOS side of window_manager briefly, but could not find an obvious workaround to propose. Apologies!

**Comment by damywise** [comment]
https://github.com/Adrian-Samoticha/macos_window_utils.dart/issues/12
https://github.com/flutter/flutter/issues/119132

**Comment by damywise** [comment]
Okay, found the fix. Not sure how to include it in `window_manager`. Maybe just add instructions to README.md.
Fix:
1. Use `macos_window_utils` or `flutter_acrylic` (`macos_window_utils`) is included in `flutter_acrylic` and [follow the instructions](https://github.com/Adrian-Samoticha/macos_window_utils.dart#getting-started)
2. If you don't use `macos_window_utils`:
Simply add this line in `MainFlutterWindow.swift`
```swift
        flutterViewController.backgroundColor = .clear
```
like so:
```diff
//...
        let flutterViewController = FlutterViewController.init()
+       flutterViewController.backgroundColor = .clear
        let windowFrame = self.frame
        self.contentViewController = flutterViewController
        self.setFrame(windowFrame, display: true)

        RegisterGeneratedPlugins(registry: flutterViewController)

        super.awakeFromNib()
    }
//...
```

**Comment by Adrian-Samoticha** [comment]
> Okay, found the fix. Not sure how to include it in `window_manager`. Maybe just add instructions to README.md. Fix:
> 
> 1. Use `macos_window_utils` or `flutter_acrylic` (`macos_window_utils`) is included in `flutter_acrylic` and [follow the instructions](https://github.com/Adrian-Samoticha/macos_window_utils.dart#getting-started)
>    (later, when the fix finally landed there)
> 2. If you don't use `macos_window_utils`:
>    Simply add this line in `MainFlutterWindow.swift`
> 
> ```swift
>         flutterViewController.backgroundColor = .clear
> ```
> 
> like so:
> 
> ```diff
> //...
>         let flutterViewController = FlutterViewController.init()
> +       flutterViewController.backgroundColor = .clear
>         let windowFrame = self.frame
>         self.contentViewController = flutterViewController
>         self.setFrame(windowFrame, display: true)
> 
>         RegisterGeneratedPlugins(registry: flutterViewController)
> 
>         super.awakeFromNib()
>     }
> //...
> ```

Keep in mind that this will make your package incompatible with Flutter versions below 3.7.0, so be sure to update your `pubspec.yaml` file accordingly.

**Comment by damywise** [comment]
Oh yeah, I wanted to ask about that. Why did you bump the minimum Flutter version?

**Comment by damywise** [comment]
Ohh `FlutterViewController`'s `backgroundColor`wasn't there before 3.7.0

**Comment by elincoln** [comment]
So in https://github.com/flutter/flutter/issues/119132 they mention setting the backgroundColor via a Widget... well, there is no Widget that applies a color to the FlutterView that I can tell.

But it led me to an alternative workaround for this package, one that doesn't require bumping minimum Flutter version:

Changes to WindowManager.swift:
```diff
public class WindowManager: NSObject, NSWindowDelegate {
//...
+    public var flutterView: NSView?;
//...
    public func setBackgroundColor(_ args: [String: Any]) {
+       flutterView?.layer?.backgroundColor = nil; // remove FlutterView's hardcoded black bg in 3.7.0.

        let backgroundColorA = args["backgroundColorA"] as! Int
//...
```

and changes to WindowManagerPlugin.swift:

```diff
public class WindowManagerPlugin: NSObject, FlutterPlugin {
//...
    private func ensureInitialized() {
        if (!_inited) {
+            windowManager.flutterView = self.registrar.view
            windowManager.mainWindow = mainWindow
//...
```

(I don't mind the README solution either, just wanted to contribute in some way. Thanks for your help on this!)
