### ISSUE TITLE
Title bar text and icon color overlaps background color so that it cannot be seen

### ISSUE THREAD

**Issue by wilinz** [leanflutter/window_manager#301]
```dart
 WidgetsFlutterBinding.ensureInitialized();
  if (PlatformUtil.isDesktop()) {
    // 必须加上这一行。
    await windowManager.ensureInitialized();
    WindowOptions windowOptions = WindowOptions(
      size: Size(480, 920),
      center: true,
      backgroundColor: Colors.white,
      skipTaskbar: false,
      titleBarStyle: TitleBarStyle.normal,
    );

    windowManager.waitUntilReadyToShow(windowOptions, () async {
      await windowManager.setMinimizable(true);
      await windowManager.setAlignment(Alignment.centerRight);
      await windowManager.setMaximizable(false);
      await windowManager.setResizable(false);
      // await windowManager.setTitleBarStyle(TitleBarStyle.normal,windowButtonVisibility: true);
      await windowManager.show();
      await windowManager.focus();
    });
  }
```
![image](https://user-images.githubusercontent.com/59408438/221194930-947d3245-2eab-4930-ac1d-9fdeef6038bc.png)
![image](https://user-images.githubusercontent.com/59408438/221194991-7c5a8a3e-08d9-46fc-b405-e26b008ced49.png)

**Comment by kolyneh** [comment]
通过`TitleBarStyle.normal`使用原生TitleBar时，需要先设置`Brightness`如下：

```dart
/// Set up window brightness base on your theme mode.
await WindowManager.instance.setBrightness(Brightness.light);
await WindowManager.instance.setTitleBarStyle(TitleBarStyle.normal);
```

**Comment by kevinxxq** [comment]
Hi @kolyneh 
I have this problem on recent win11, after changing the thememode, the title is ok but the icons are still not visible.

![image](https://user-images.githubusercontent.com/55800697/236357781-6f9993c0-dde1-4f87-ad0b-40eda774bb80.png)

Thank you.

**Comment by kolyneh** [comment]
Hi @kevinxxq ,
Is your theme mode automatically changed flowing the system?

You need to update your `native code` to handle theme mode change on recent Windows.
You can create a new temp project then diff it with your project to see whats changed in `./windows/runner/win32_window.cpp`. 
There will be a new method in it call `UpdateTheme` to handle the system theme mode change.
Them in your `dart code` you should let your top level widget state extends with `WidgetsBindingObserver` and override `didChangePlatformBrightness` method:
```dart
@override
void didChangePlatformBrightness(){
    super.didChangePlatformBrightness();

    final brightness  = window.platformBrightness;
    
   /// Set up window brightness follow system theme mode.
   await WindowManager.instance.setBrightness(brightness);
   await WindowManager.instance.setTitleBarStyle(TitleBarStyle.normal);
}

```
Hope it helps.

**Comment by kevinxxq** [comment]
@kolyneh 
Thank you, solve it perfectly.
