### ISSUE TITLE
How to determine if setPosition will place windows in visible screen?

### ISSUE THREAD

**Issue by gslender** [leanflutter/window_manager#303]
There does not seem to be a method for determining the available visible screen resolution, so if you wish to restore the window to the previously set size/position, you cannot be sure that you're not restoring it to some off-screen location (in cases where the user has a 2nd screen on a laptop, but is currently not connected).

What solution would you propose for either a) determining the screen resolutions have changed, or b) ensuring you are not restoring the window to an invisible location?

**Comment by animator** [comment]
+1 Any way to determine available visible screen size?

**Comment by lijy91** [comment]
`window_manager` using [`screen_retriever`](https://pub.dev/packages/screen_retriever) To retrieve the visible screen size and coordinates of the screen, I think this package should be able to solve your problem.
