### ISSUE TITLE
windows多屏幕bug（两台屏幕缩放设置倍率不同）

### ISSUE THREAD

**Issue by xiaoyang886** [leanflutter/window_manager#304]
在主屏幕（1.5缩放倍率）设置应用Size（800*400）最小为最小Size为（700*300），应用显示在屏幕上为（1200*600），把应用拖动到1缩放倍率的显示器上，应该显示为800*400，目前显示为1050*450（700*1.5，300*1.5），当前应用大小能根据缩放倍率自适应，最小分辨率不能根据屏幕缩放倍率自适应

**Comment by lijy91** [comment]
请更新到 `0.3.2` ，已由下面的 https://github.com/leanflutter/window_manager/pull/231 修复
