### ISSUE TITLE
Indeterminate progress bars don't work (on macOS)

### ISSUE THREAD

**Issue by ricardoboss** [leanflutter/window_manager#308]
As I found out when investigating #307, the indeterminate progress bars don't work.

To test this, I called `windowManager.setProgressBar(2)`. This is the result:
![image](https://user-images.githubusercontent.com/6266356/224041812-36c9e2cb-9c56-4b2e-a556-88a979857580.png)

I suppose it should show an animation instead of staying at a value that looks like 0.

**Comment by lijy91** [comment]
It only supports values from 0 ~ 1.0, I will add an assertion to check if the progress value are correct
