### ISSUE TITLE
click a button wrapered by DragToMoveArea feel a little 'lag'?

### ISSUE THREAD

**Issue by gkdgo** [leanflutter/window_manager#309]
It seems the DragToMoveArea prevent click signal to wrapered button
I want to know why and how to solve it

**Comment by damywise** [comment]
put `DragToMoveArea` behind the button, not in front of it

**Comment by gkdgo** [comment]
> put `DragToMoveArea` behind the button, not in front of it

thank u, but actually  I want to make the AppBar movable ,so I wrapped it by DragToMoveArea, and there are some buttons on AppBar.
if I make DragToMoveArea a child of Button , the movable area will be small , but I want the whole AppBar movable

**Comment by lijy91** [comment]
Use `DragToMoveArea` wrap `AppBar`, like this
```dart
Scaffold(
  appBar: PreferredSize(
    preferredSize: const Size.fromHeight(kToolbarHeight),
    child: DragToMoveArea(
      child: AppBar(
        title: const Text('window_manager_example'),
      ),
    ),
  ),
  body: Center(),
),
```
