### ISSUE TITLE
鼠标移到顶部边界, 不会触发拉伸窗口的箭头, 不能改变窗口大小

### ISSUE THREAD

**Issue by j787701730** [leanflutter/window_manager#31]
鼠标移到顶部边界, 不会触发拉伸窗口的箭头, 不能改变窗口大小, 其他三个方向都正常. 
`
[√] Flutter (Channel beta, 2.9.0-0.1.pre, on Microsoft Windows [Version 10.0.19044.1415], locale zh-CN)
    • Flutter version 2.9.0-0.1.pre at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (3 weeks ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1

  cupertino_icons: ^1.0.2
  win_toast: ^0.0.2
  get_storage: ^2.0.3
  flutter_window_close: ^0.2.0
  window_manager: ^0.1.1
  tray_manager: ^0.1.2
  file_picker: ^4.3.0
`

**Comment by lijy91** [comment]
在默认模式下该问题已经修复，在隐藏标题栏的模式还存在该问题，请更新到 v0.1.3
