### ISSUE TITLE
Get MainWindow Hwnd

### ISSUE THREAD

**Issue by Eerey** [leanflutter/window_manager#312]
Hi,
I'm using some `win32`-Functions for my windows flutter project.
How do I get the main window handle / HWND id?

For example I want to use `GetWindowLongPtr`, but it requires the window handle.

**Comment by lijy91** [comment]
I don't think this should be provided by the plugin. You can use the `GetCurrentProcess` method of the `win32` package to get it.

```dart
int hWnd = GetCurrentProcess();
GetWindowLongPtr(hWnd, GWL_EXSTYLE);
```

**Comment by Eerey** [comment]
@lijy91 can you reopen the ticket? Your proposed method does not fulfill the requirements.

**Comment by damywise** [comment]
From https://github.com/dart-windows/win32/issues/336

>  try retrieving handle by flutter's app class name(FLUTTER_RUNNER_WIN32_WINDOW) with FindWindowEx function.

> One more way to retrieve handle is EnumWindows. You can call GetWindowThreadProcessId for each window and compare it with GetCurrentProcessId()
