### ISSUE TITLE
Setting Extended Window Style (e.g. WS_EX_NOACTIVATE)

### ISSUE THREAD

**Issue by Eerey** [leanflutter/window_manager#313]
Hi,
with `win32` it is possible to change the current window style like that:

```dart
  SetWindowLongPtr(hwnd, GWL_EXSTYLE, WS_EX_NOACTIVATE);
```

Is it possible to to that with window_manager?

**Comment by lijy91** [comment]
Maybe you need a setFocusable method.

Please follow up Issue https://github.com/leanflutter/window_manager/issues/317
