### ISSUE TITLE
Is there a way to make the VirtualWindowFrame transparent 

### ISSUE THREAD

**Issue by oSethoum** [leanflutter/window_manager#322]
Hi, am looking for a way to make the `VirtualWindowFrame` transparent, the need of it because in windows when the window is `frameless` it's not resizable. 
![image](https://user-images.githubusercontent.com/88779394/228854292-eda982a6-632d-46eb-9994-8c62d37e18e0.png)

**Comment by lijy91** [comment]
Please update to 0.3.2, fixed by https://github.com/leanflutter/window_manager/pull/318
