### ISSUE TITLE
再次启动app 应该记录下上次调整的size和offset位置

### ISSUE THREAD

**Issue by zhangruiyu** [leanflutter/window_manager#324]
这样感觉会体验更好

**Comment by lijy91** [comment]
可以配合 [hidden-at-launch](https://github.com/leanflutter/window_manager#hidden-at-launch) 自行实现。

**Comment by zhangruiyu** [comment]
很抱歉再次打扰,对于我们这种没有原生经验方面的人来说,这个实现不太容易,而且这个需求其实是正常应用都存在的.
由于我不了解原生部分,我就在flutter里通过sp记录offset和size,但是体验并不好
