### ISSUE TITLE
WindowButtons not visible when window is not in focus

### ISSUE THREAD

**Issue by ANix02** [leanflutter/window_manager#325]
The Buttons for closing, minimizing and maximizing aren't visible when you e.g. click outside of the flutter app and loose focus. The movement you hover over the position where those buttons should be, they are visible again.

**Comment by lijy91** [comment]
This should be the default behavior of macOS.

**Comment by ANix02** [comment]
@lijy91 No the default behavior is that the button themselves are still visible. They only loose color. Example attached of VS Code app.
![image](https://user-images.githubusercontent.com/67485870/232324444-6520ab55-e172-48e1-b9ec-74b750166112.png)

![image](https://user-images.githubusercontent.com/67485870/232324459-8d4c5a0e-a6a2-4ab6-85f6-4c52008c9c85.png)
