### ISSUE TITLE
Add SystemTray

### ISSUE THREAD

**Issue by softplace-io** [leanflutter/window_manager#328]
Hello, guys!

I observed that we can hide and display the program (desktop).
I was wondering if it is possible to put beside the clock (Systemtray)?

```
void _hidewindow () {
   windowmanager.hide () // will hide the window and the app will be running in the background
}

void _showwindow () {
   windowmanager.show () // will show the window
}
```

**Comment by lijy91** [comment]
Please use https://github.com/leanflutter/tray_manager
