### ISSUE TITLE
native_context_menu wrong position when setTitleBarStyle to "hidden"

### ISSUE THREAD

**Issue by dodatw** [leanflutter/window_manager#33]
Hi @lijy91

setTitleBarStyle is work, it help me hide the title bar.
But I found a issue when I use native_context_menu.
If I use native_context_menu when title bar hidden. the menus position is wrong. it always at button of screen.

Thanks.

**Comment by lijy91** [comment]
![IMG_20220219_204114.jpg](https://user-images.githubusercontent.com/3889523/154801237-983db546-b740-4856-91f3-74ecf22d4a41.jpg)

**Comment by dodatw** [comment]
This issue only reproduce on Windows and release build

**Comment by lijy91** [comment]
@dodatw I fixed this for `native_context_menu` and created pr https://github.com/lesnitsky/native_context_menu/pull/14 .
