### ISSUE TITLE
Fullscreen problem: previous screen visible at the bottom when pushing new screen

### ISSUE THREAD

**Issue by Bullets-jyr** [leanflutter/window_manager#334]
![235342108-f05b5688-c73b-465e-87fc-e9cd3109fbb5](https://user-images.githubusercontent.com/117099209/236008850-d1f8676f-aa69-4671-8a3b-9b6ca45d6cba.png)

This is a confirmed issue when the video player is fullscreen and back to original size, or if you make it fullscreen from original size.
The main window of windows looks like this.
Is there any way to solve it?
When switching from full-screen mode to the previous mode or from the previous mode to full-screen mode, the blue main window is visible.
Is it possible to make the blue main window completely transparent?
A light blue border is visible in the process of quickly switching between full screen and full screen.

**Comment by lijy91** [comment]
Duplicate https://github.com/leanflutter/window_manager/issues/330
