### ISSUE TITLE
setMinimumSize not working on macOS

### ISSUE THREAD

**Issue by git-n-pissed** [leanflutter/window_manager#335]
The following code is being called in the `main` method right before `runApp` is called:

```
  // Don't allow the app window to be too small
  if(Platform.isWindows || Platform.isMacOS) {
    await windowManager.setMinimumSize(const Size(640, 480));
  }
```

Works as expected on Windows, but results in this error on macOS:

`window_manager/WindowManager.swift:44: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

**Comment by damywise** [comment]
Hey, would you mind sharing a minimum reproducible example with me?
Also, have you tried that the one in example works as expected?
I'm unable to reproduce this in MacOS Ventura 13.2.1 (22D68).
Thanks!

**Comment by temeddix** [comment]
Having the same issue here, I'm using macOS Ventura 13.2.1 on macbook pro 15-inch 2017.

**Comment by temeddix** [comment]
I tried changing versions.

On 0.3.0
```
window_manager/WindowManager.swift:44: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```
0.3.4
```
window_manager/WindowManager.swift:60: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

**Comment by temeddix** [comment]
Oops, it was because I missed out the following line:
```
await windowManager.ensureInitialized();
```

**Comment by git-n-pissed** [comment]
> Oops, it was because I missed out the following line:
> 
> ```dart
> await windowManager.ensureInitialized();
> ```
> 
> So this is not a bug, it's a mistake. After I added this line, it works like a charm.

I haven't used that line before (doesn't appear to be needed for Android or Windows builds).  I had switched to `desktop_window` package, but I'll try `window_manager` again and use `ensureInitialized` to see if that fixes the issue for me as well.
