### ISSUE TITLE
再次启动app 应该记录下上次调整的size和offset位置

### ISSUE THREAD

**Issue by zhangruiyu** [leanflutter/window_manager#336]
很抱歉再次打扰,对于我们这种没有原生经验方面的人来说,通过  hidden-at-launch 这个实现然后自己修改不太容易,这个需求其实是正常应用都存在的.
由于我不了解原生部分,我就在flutter里通过sp记录offset和size,然后打开应用后修改,但是效果并不好
希望官方能给出方案

**Comment by youxiachai** [comment]
@zhangruiyu 你这个需求只能改原生, 首帧渲染,肯定是在windwos插件那里的..其实hidden-at-launch  ,你就是删一行代码就行了..为啥会觉得不太容易修改...

**Comment by zhangruiyu** [comment]
额 完全没摸索过这个  而且好像要写3端 我比较菜 确实是不会写3端的东西啊,首先肯定要记录保存到某个文件里,然后再去说的那个方法里做修改,如果插件提供选项那么肯定是最好的

**Comment by lijy91** [comment]
请自行实现
