### ISSUE TITLE
[macOS]The app exit unexpectedly after executing hide().

### ISSUE THREAD

**Issue by jeson-jin** [leanflutter/window_manager#337]
macos ventura 13.3 environment, after executing hide(), the app quits unexpectedly. 
Error message: Lost connection to device.

**Comment by damywise** [comment]
Hey, would you mind sharing a minimum reproducible example with me?
Also, have you tried that the one in example works as expected?
I'm unable to reproduce this in MacOS Ventura 13.2.1 (22D68).
Thanks!

**Comment by jeson-jin** [comment]
> Hey, would you mind sharing a minimum reproducible example with me?
> Also, have you tried that the one in example works as expected?
> I'm unable to reproduce this in MacOS Ventura 13.2.1 (22D68).
> Thanks!

### Environment

[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/jeson/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 周前), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/jeson/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.3.1 22E772610a darwin-arm64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

### Source Code

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await windowManager.ensureInitialized();

  WindowOptions windowOptions = const WindowOptions(
    size: Size(800, 600),
    center: true,
    backgroundColor: Colors.transparent, // 窗口透明
    skipTaskbar: false, // 不显示app运行图标
    titleBarStyle: TitleBarStyle.hidden, // 标题栏
    windowButtonVisibility: true, // 标题栏上控制按钮
  );
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    // await windowManager.setAsFrameless(); // 无边框窗口
    await windowManager.show();
    await windowManager.focus();
  });

  runApp(const MyApp());
}

///
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    final virtualWindowFrameBuilder = VirtualWindowFrameInit();

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      builder: (context, child) {
        child = virtualWindowFrameBuilder(context, child);
        return child;
      },
      home: Homepage(),
    );
  }
}

///
class Homepage extends StatefulWidget {
  Homepage({super.key});

  final _debouncer = Debouncer(milliseconds: 500);

  @override
  State<Homepage> createState() => _HomepageState();
}

class _HomepageState extends State<Homepage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          ElevatedButton(
            child: const Text('Hide'),
            onPressed: () => windowManager.hide(),
          ),
          const SizedBox(height: 10),
          ElevatedButton(
            child: const Text('Hide with Debounce'),
            onPressed: () {
              windowManager.focus();
              widget._debouncer.run(() async {
                await windowManager.hide();
              });
            },
          ),
        ],
      ),
    );
  }
}

///
class Debouncer {
  final int milliseconds;
  VoidCallback action = () {};
  Timer _timer = Timer(Duration.zero, () {});
  Debouncer({required this.milliseconds});
  run(VoidCallback action) {
    _timer.cancel();
    _timer = Timer(Duration(milliseconds: milliseconds), action);
  }
}

### Run the result

Lost connection to device.

**Comment by damywise** [comment]
Hello, I have tried to run your code but unfortunately I can't reproduce your problem. The app doesn't quit, it works without any error.

Please try the example app and tell if the `hide()` function also errors there.

**Comment by sgehrman** [comment]
I just upgraded flutter and when I hide a window the app quits.  I've only tested linux.

**Comment by jeson-jin** [comment]
Thanks all !

**Comment by sgehrman** [comment]
> Thanks all !
> 
> I've solved it.
> 
> There are instructions in the read [README.md](https://github.com/leanflutter/window_manager/blob/main/README.md)

where in the readme?
