### ISSUE TITLE
 I just upgraded flutter and when I hide a window the app quits. I've only tested linux.

### ISSUE THREAD

**Issue by sgehrman** [leanflutter/window_manager#338]
I just upgraded flutter and when I close a window onWindowClose never gets called and the app quits. I've only tested linux.

It worked before the latest flutter released today.

**Comment by sgehrman** [comment]
It's simple to reproduce.  This works fine in Flutter 3.7, but it quits the app on 3.10.

Modify the example app.
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await windowManager.ensureInitialized();
// add setPreventClose(true) ############
  await windowManager.setPreventClose(true);
```
```
  @override
  void onWindowClose() {
    windowManager.hide();
  }
```

**Comment by sgehrman** [comment]
I tried a bunch of stuff and couldn't fix it.

One thing I noticed:
  g_signal_connect(get_window(plugin), "delete_event",
                   G_CALLBACK(on_window_close), plugin);

why "delete_event" and not "delete-event"?  I tried delete-event and it made no difference, but wondering if that's a bug.

**Comment by sgehrman** [comment]
?

**Comment by lijy91** [comment]
Unfortunately, the engine prevented WindowManager from listening to this event.
https://github.com/flutter/engine/pull/40033/files#r1200216166

**Comment by tomekit** [comment]
Hi @sgehrman,

I am wondering if you've managed to get it working? I am facing the same issue on Ubuntu 22.10 and latest flutter (3.10.4).

Trying to make: `setPreventClose` and `onWindowClose` work together to suppress the close button and ask user if they want to minimize app instead. 

I've "blindly" added the: `g_signal_connect(window, "delete-event", G_CALLBACK(gtk_widget_hide_on_delete), NULL);` line in the: `my_application.cc`, but it has no effect really -> Clickin the x button in the title bar closes the app immediately.

**Comment by lijy91** [comment]
Please update to 0.3.5, this version has already fixed this issue
