### ISSUE TITLE
Restore window state

### ISSUE THREAD

**Issue by CodeDoctorDE** [leanflutter/window_manager#344]
Currently, if the app starts, it doesn't restore to the previous window state. See https://github.com/LinwoodDev/Butterfly/issues/274 
For example here: https://github.com/leanflutter/window_manager/blob/main/lib/src/window_manager.dart#L112 This will override the current size if it's maximized

**Comment by lijy91** [comment]
Please set to Hidden at launch and restore your saved state values during the hiding phase.

**Comment by CodeDoctorDE** [comment]
You mean I should save the position and size in a shared_preference and load them after that?
Is there no native way to do this?

**Comment by lijy91** [comment]
Yes, I think this is the easiest way to do it. I don't want to use native to implement this function, it will take me a lot of time and is not worth it.
