### ISSUE TITLE
can you create a public function for get display size of device?

### ISSUE THREAD

**Issue by shixin627** [leanflutter/window_manager#346]
can you create a public function for get display size of device?

Future<Size> getDisplaySize() async {
  Display primaryDisplay = await screenRetriever.getPrimaryDisplay();
  num visibleWidth = primaryDisplay.size.width;
  num visibleHeight = primaryDisplay.size.height;

  return Size(visibleWidth.toDouble(), visibleHeight.toDouble());
}

**Comment by lijy91** [comment]
Please use this plugin https://github.com/leanflutter/screen_retriever
