### ISSUE TITLE
Is there a way to have square corners in OSX?

### ISSUE THREAD

**Issue by naychrist** [leanflutter/window_manager#350]
I have a frameless app that I want to span multiple displays and appear fullscreen. The only imperfection after setting the OSX menu bar to auto hide and my flutter app to frameless is the rounded corners. Googling has turned up no way to do this in the NSWindow so the OS may just not allow this but thought I would ask the brains trust here.

I am using this for kiosk/signage type uses. If the wallpaper is an issue I can set the window to bleed off the edges but that's an awful hack so would love an alternative. Will eventually need to do this on windows too but not sure it's an issue there.

**Comment by lijy91** [comment]
You can use the `setAsFrameless` method to modify the window to borderless and use Flutter to draw a right angle background
