### ISSUE TITLE
macos 关闭按钮是否能调整上边距

### ISSUE THREAD

**Issue by wanghongenpin** [leanflutter/window_manager#353]
<img width="373" alt="image" src="https://github.com/leanflutter/window_manager/assets/24794200/4d7028da-3f1d-4bff-97c2-fa1feb5a4aef">
<img width="325" alt="image" src="https://github.com/leanflutter/window_manager/assets/24794200/f94ef6a5-54c0-4310-9c13-24f65e2ebdb1">

可以调整这三个按钮上边距什么的吗

**Comment by 89pleasure** [comment]
I also would like to be able to set a padding or an alignment.center on main/cross axis.

**Comment by lijy91** [comment]
可以参考这行代码，可以修改成右图的效果
https://github.com/leanflutter/anyinspect_app/blob/0f4db9b5e33329987729c15750e9757ec381ae6a/macos/Runner/MainFlutterWindow.swift#L12
