### ISSUE TITLE
windows上全屏逻辑比较奇怪

### ISSUE THREAD

**Issue by shuax** [leanflutter/window_manager#363]
全屏不知道为什么要调用`::ShowWindow(window, SW_MAXIMIZE);`，恢复的时候又会调用`::ShowWindow(window, SW_RESTORE);`。照理说全屏应该和最大化没关系，现在如果已经是最大化的窗口全屏后恢复，会改变2次大小，看起来比较闪烁。

**Comment by shuax** [comment]
可以参考：https://github.com/chromium/chromium/blob/38ae7c3b4ad5c8ae169209adb2f3113e2144ee8d/ui/views/win/fullscreen_handler.cc#L60

**Comment by 1232209** [comment]
> 全屏不知道为什么要调用`::ShowWindow(window, SW_MAXIMIZE);`，恢复的时候又会调用`::ShowWindow(window, SW_RESTORE);`。照理说全屏应该和最大化没关系，现在如果已经是最大化的窗口全屏后恢复，会改变2次大小，看起来比较闪烁。

同样的问题，闪烁在windows上特别明显
