### ISSUE TITLE
[windows 7] 0.3.2 version show missing api-ms-win-shcore-scaling-l1-1-1.dll error

### ISSUE THREAD

**Issue by yeleibo** [leanflutter/window_manager#366]
![3325f50544f7b619b15063a582e000a](https://github.com/leanflutter/window_manager/assets/22091417/0fba0db6-97e1-4894-9468-c00eddcacf46)

**Comment by kevinxxq** [comment]
Hi,
the problem should be from 0.3.4->0.3.5.

Copy a dll to system32 will bring the issue to 0xc000007b.

If possible, please fix it as @https://github.com/flutter/engine/pull/30699 

Thank you.

**Comment by Tienisto** [comment]
I fixed this in #388

**Comment by lijy91** [comment]
Fixed, please update to 0.3.6
