### ISSUE TITLE
android

### ISSUE THREAD

**Issue by longfit** [leanflutter/window_manager#368]
I have problem debug android platform which will be paused
on exception
Future isMaximized() async {
return await _channel.invokeMethod('isMaximized');
}

how to avoid when i switch the android platform

**Comment by damywise** [comment]
`if (Platform.isAndroid) {...}`

**Comment by lijy91** [comment]
I recently developed a new package [uni_platform](https://pub.dev/packages/uni_platform), you can try using it

```dart
String platformType = UniPlatform.call<String>(
  android: () => 'Android',
  fuchsia: () => 'Fuchsia',
  iOS: () => 'iOS',
  linux: () => 'Linux',
  macOS: () => 'macOS',
  windows: () => 'Windows',
  web: () => 'Web',
  otherwise: () => 'Unknown',
);
```
