### ISSUE TITLE
Additional window  captions

### ISSUE THREAD

**Issue by ewilliams0305** [leanflutter/window_manager#373]
![image](https://github.com/leanflutter/window_manager/assets/53901011/26fad185-2dc7-4545-9dd0-7c90efaeadf8)

Beyond just the standard min/max/close window captions, several applications commonly use this space for notification, options, and generally any item that want displayed on the entire ui. I was able to accomplish this by adding an optional array or custom caption buttons the WindowCaption. If this sounds like a feature that aligns with the overall mantra of the window manager package I will happily create a PR to add this capability. 

```
class WindowCaption extends StatefulWidget {
  const WindowCaption({
    Key? key,
    this.title,
    this.backgroundColor,
    this.brightness,
    /// insert array of captions here this.Children<Caption>[]
  }) : super(key: key);
```

**Comment by lijy91** [comment]
This widget will be a separate package in a future version. Now, you can copy the code of this widget to your project for customization.
