### ISSUE TITLE
如何实现点击某个按钮后释放app的焦点，将焦点转到前一个窗口程序？

### ISSUE THREAD

**Issue by lucasjinreal** [leanflutter/window_manager#376]
有这么一个需求：

用户在flutter app里面输入一段文字，然后enter或者点击某个按钮，此时就hide 或者 取消app的焦点，还给上一个窗口应用的input box。

这个应该如何实现啊

**Comment by lijy91** [comment]
window_manager 只能处理当前窗口，如果要实现这个功能，如果是 Windows 建议看看 win32 包。
