### ISSUE TITLE
Windows单实例应用，窗口标题设置为中文时无效

### ISSUE THREAD

**Issue by 6ag** [leanflutter/window_manager#382]
`HWND hwnd = ::FindWindow(L"FLUTTER_RUNNER_WIN32_WINDOW", L"XXX中文标题");` 一直为空。

**Comment by 6ag** [comment]
我知道这不是 `window_manager` 的问题，可能是由于编码问题导致的，请问需要如何设置中文标题呢

**Comment by lijy91** [comment]
参考一下这里 https://github.com/leanflutter/window_manager/blob/8caf178456968fee5ee82dd90d95a01dd4b1137b/windows/window_manager.cpp#L868-L874

**Comment by 6ag** [comment]
@lijy91 已解决，谢谢
