### ISSUE TITLE
Macos setAlwaysOnTop 无法在全屏应用上方

### ISSUE THREAD

**Issue by whyming** [leanflutter/window_manager#386]
```
 await windowManager.setAsFrameless();
 await windowManager.setVisibleOnAllWorkspaces(true, visibleOnFullScreen: true);
  await windowManager.setAlwaysOnTop(true);
```
如题，窗口无法悬浮在其他应用上方，包括已经全屏的应用，达到“聚焦搜索”那种效果
是需要设置其他配置吗？还是需要修改swift代码？还是目前不支持啊。

**Comment by lijy91** [comment]
参考这里 将NSWindow 改成NSPanel

https://github.com/biyidev/biyi/blob/main/apps/biyi_app/macos/Runner/MainFlutterWindow.swift
