### ISSUE TITLE
question about window sleep mode

### ISSUE THREAD

**Issue by minn-ee** [leanflutter/window_manager#393]
Hello, thanks for the good plugin.
Is there any method for windows sleep event?
I want to refresh my windows app after the windows sleep mode is over.
I'll look forward to get any answer!

**Comment by maxfornacon** [comment]
I found this package https://pub.dev/packages/flutter_desktop_sleep . It's a bit poorly documented but I got it to work on MacOS. On Windows I'm not sure yet.

**Comment by lijy91** [comment]
This [flutter_desktop_sleep](https://pub.dev/packages/flutter_desktop_sleep) plugin already supports Windows, you can use it, window_manager will not add sleep related features temporarily
