### ISSUE TITLE
Is there a way using this lib implement window like this app?

### ISSUE THREAD

**Issue by lucasjinreal** [leanflutter/window_manager#394]
<img width="1061" alt="image" src="https://github.com/leanflutter/window_manager/assets/21303438/138c0d3a-8a25-4e69-9bdd-c6ffbb807d51">

the window height are dynamically extended along with the messages.

Currently, I see. all flutter desktop are fixed, can not dynamically extend height, except you drag to resize your window.

**Comment by lijy91** [comment]
Please refer to https://github.com/biyidev/biyi/blob/87be06a18cadb1d9be06905a8ffe07c1dc1a4b32/apps/biyi_app/lib/pages/desktop_popup/desktop_popup.dart#L332-L380
