### ISSUE TITLE
onWindowEnterFullScreen/onWindowLeaveFullScreen not work any more on windows

### ISSUE THREAD

**Issue by nonebyte** [leanflutter/window_manager#396]
ver 0.3.6 fullscreen callback onWindowEnterFullScreen/onWindowLeaveFullScreen not work any more,  when fullscreen status  change only  onWindowMaximize/onWindowUnmaximize called .

**Comment by damywise** [comment]
Sorry, yeah I can definitely reproduce this in the example app.
I will hopefully make a PR soon.
