### ISSUE TITLE
MACOSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by wanyangye** [leanflutter/window_manager#398]
Hello, I have encountered a compilation error, my environment is MacOS14,Xcode15.
flutter/client/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'window_manager' from project 'Pods')

**Comment by lijy91** [comment]
Please set it to 10.14
