### ISSUE TITLE
windowManager.startDragging can't work

### ISSUE THREAD

**Issue by autumn-moon-py** [leanflutter/window_manager#399]
i want use my titleBar,but i can't drag
i add a widget for drag, this's my code,but it can't drag
```
GestureDetector(
            onTap: () async {
              await windowManager.startDragging();
            },
            onLongPress: () async {
              await windowManager.startDragging();
            },
            child: Container(
                color: Colors.red,
                width: double.infinity,
                child: sb(height: 30)));
```
![image](https://github.com/leanflutter/window_manager/assets/77103327/33e517de-abce-4563-9d32-7e3ee07aee33)

**Comment by jihchao** [comment]
use windowManager.startDragging() in onPanStart event.
if you are using in a transparent area, please set the behavior to  HitTestBehavior.translucent 

```dart
GestureDetector(
                          behavior: HitTestBehavior.translucent,
                          onPanStart: (details) {
                            windowManager.startDragging();
                          },
                          child: Container(
                            height: titleBarHeight,
                            width: ScreenUtil.screenWidth,
                          ),
                        ),
```

**Comment by autumn-moon-py** [comment]
> use windowManager.startDragging() in onPanStart event.在 onPanStart 事件中使用 windowManager.startDragging（）。 if you are using in a transparent area, please set the behavior to HitTestBehavior.translucent如果您在透明区域使用，请将行为设置为 HitTestBehavior.半透明
> 
> ```dart
> GestureDetector(
>                           behavior: HitTestBehavior.translucent,
>                           onPanStart: (details) {
>                             windowManager.startDragging();
>                           },
>                           child: Container(
>                             height: titleBarHeight,
>                             width: ScreenUtil.screenWidth,
>                           ),
>                         ),
> ```

thank you
