### ISSUE TITLE
Fullscreen on macOS can be dismissed with `esc` key

### ISSUE THREAD

**Issue by chaeMil** [leanflutter/window_manager#403]
Fullscreen on macOS can be dismissed with `esc` key. There's no way to prevent this from Flutter par. Can something be added from the library side to handle this, please?

**Comment by SpaceXM** [comment]
the only effective way i found is to use a focus (or keyboard listener) to handle the key and wrap all

`Focus(
        focusNode: FocusNode(),
        onKey: (node, event) {
          if (event is RawKeyDownEvent) {
            if (event.logicalKey.keyLabel == 'Escape' ) {
            return KeyEventResult.handled;
}
return KeyEventResult.ignored;
}
return KeyEventResult.ignored;
}, 
child:.....
`
in this way you can avoid the default escape function by returning to the system a fake handled

**Comment by chaeMil** [comment]
Yeah this works! thanks :)
