### ISSUE TITLE
how to cancel setAsFrameless ?

### ISSUE THREAD

**Issue by keepgagaga** [leanflutter/window_manager#407]
I set title bar hiden by setAsFrameless, but don't know how to set it show, this package have show title bar method ?

**Comment by damywise** [comment]
to set title bar style, use `setTitleBarStyle`
to undo `setAsFrameless`, use `setTitleBarStyle(TitleBarStyle.normal)`

**Comment by damywise** [comment]
I have no idea why I didn't mention it, but just calling `setTitleBarStyle` also undoes `setAsFrameless`.

**Comment by damywise** [comment]
Though in general, I don't have any idea why any of `setTitleBarStyle` or `setAsFrameless` will be called more than once

**Comment by damywise** [comment]
Hmm yea maybe you can add it to the readme?

**Comment by keepgagaga** [comment]
> Hmm yea maybe you can add it to the readme and API comment docs?

I add a pr for this, you can review it.
