### ISSUE TITLE
Stop dragging on button release

### ISSUE THREAD

**Issue by andersonpem** [leanflutter/window_manager#413]
I'm implementing a small application. I was able to start dragging, like so:
`onSecondaryLongPressDown: (details) {
            windowManager.startDragging();
},
`
But the drag persists after I release the right click button.
What would I need to implement in `onSecondaryLongPressUp: ()` for it to stop the drag action?

Thank you very much for your attention.

Flutter on Linux
OS: Ubuntu 22.04 LTS x86_64

**Comment by damywise** [comment]
Try using `onSecondaryLongPressStart` instead of `onSecondaryLongPressDown`

**Comment by lijy91** [comment]
Please call it in `onPanStart`, and it does not need to end it manually.
