### ISSUE TITLE
设置启动位置后，从默认位置闪烁到居中位置。

### ISSUE THREAD

**Issue by 944095635** [leanflutter/window_manager#418]
`
 //Windows
  if (Platform.isWindows) {

    await windowManager.ensureInitialized();

    WindowOptions windowOptions = const WindowOptions(

      size: Size(1100, 760),

      center: true,

      skipTaskbar: false,

      backgroundColor: Colors.white,

      titleBarStyle: TitleBarStyle.hidden,

    );

    windowManager.waitUntilReadyToShow(windowOptions, () async {

      await windowManager.show();

      await windowManager.focus();

    });

  }

`

当设置center: true时，窗口的初始位置 会从 默认位置闪烁到 居中，这样的体验不太好，有没有方法可以改进？

**Comment by anchao-lu** [comment]
可以 await windowManager.waitUntilReadyToShow 试试

**Comment by lijy91** [comment]
你可以查看启动时隐藏相关的文档来解决这个问题 https://github.com/leanflutter/window_manager?tab=readme-ov-file#hidden-at-launch
