### ISSUE TITLE
Transform.scale

### ISSUE THREAD

**Issue by JuanLuisNL** [leanflutter/window_manager#419]
I have a windows application, I want to apply a "Transform.scale" to the whole application for accessibility (zoom) and to adapt to small monitors (reduce). It works fine in the whole app except for the first screen. Is it possible to do something?

runApp(Transform.scale(scale: 0.8, child: const MyApp()));

![Captura](https://github.com/leanflutter/window_manager/assets/89520605/635c8bbc-a8b0-4870-b2f7-4afb92e73008)

**Comment by TomKrauss** [comment]
How about the following solution? (Of course you need to apply the scale factor to the window size also):
```
FractionallySizedBox(
      heightFactor: 1 / scaleFactor
      widthFactor: 1 / scaleFactor,
      child: Transform.scale(
        scale: scaleFactor,
        child:  MyApp()
```
