### ISSUE TITLE
初始的时候最大化窗口，再setFullScreen(false)的时候，窗口异常

### ISSUE THREAD

**Issue by ibaoyun** [leanflutter/window_manager#457]
在waitUntilReadyToShow的时候，设置fullScreen为true。这个时候发现setFullScreen(false)恢复的时候，窗口只有背景色，无任何内容，也任务栏图标也消失。windowManager.minimize();这个调用也无任何反应。
平台为windows。

**Comment by Markus43** [comment]
In english vis google translate:
When waitingUntilReadyToShow, fullScreen is set to true. At this time, when setFullScreen(false) is restored, the window only has the background color, no content, and the taskbar icon disappears. The call windowManager.minimize() also has no response. The platform is Windows.

**Comment by Markus43** [comment]
@ibaoyun  Can you close here since you re-reported in english in #458 ?

**Comment by lijy91** [comment]
与 https://github.com/leanflutter/window_manager/issues/458 重复，先关闭了
