### ISSUE TITLE
Window Error (MacOs)

### ISSUE THREAD

**Issue by SatanaKonst** [leanflutter/window_manager#471]
When I try to minimize, maximize, close the window I get an error

`window_manager/WindowManager.swift:60: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

System:
MacOs Ventura 13.6.7
Flutter 3.22.2 
Framework • revision 761747bfc5 
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by Prashant4900** [comment]
@SatanaKonst did you find any solution

**Comment by lijy91** [comment]
It seems that the ensureInitialized method is not called.
```dart
import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Must add this line.
  await windowManager.ensureInitialized();

  WindowOptions windowOptions = WindowOptions(
    size: Size(800, 600),
    center: true,
    backgroundColor: Colors.transparent,
    skipTaskbar: false,
    titleBarStyle: TitleBarStyle.hidden,
  );
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });

  runApp(MyApp());
}
```

**Comment by SatanaKonst** [comment]
yes, part of the code in the main function is lost.
Thank you
