### ISSUE TITLE
Unable to change the size in 0.4.0

### ISSUE THREAD

**Issue by JemmyWang94** [leanflutter/window_manager#483]
In version 0.3.9 of pub, I was able to drag the mouse at the edge to change the size of the application, but after updating to 0.4.0, I was unable to change the size of the application by dragging the edge.    Not change anything. just update to 0.4.0.

**Comment by JemmyWang94** [comment]
await windowManager.ensureInitialized();

      WindowOptions windowOptions = const WindowOptions(
        center: true,
        backgroundColor: Colors.transparent,
        skipTaskbar: false,
        titleBarStyle: TitleBarStyle.hidden,
      );
      await windowManager.waitUntilReadyToShow(windowOptions, () async {
        await windowManager.show();
        await windowManager.focus();
      });

**Comment by JemmyWang94** [comment]
yes, I have updated flutter 3.24, but it is the same result in 3.24 and 3.22.3.  
When I set titleBarStyle: TitleBarStyle.normal, it works well, Thanks your advise. But I need to hide titlebar. 
It's amazing why this phenomenon occurs？

**Comment by clong1995** [comment]
me to

**Comment by unvictory2** [comment]
I have the same issue, did you manage to fix it? I also want to keep the titlebar hidden, but the window moveable/resizeable. I tried `await windowManager.setResizable(true);` and `await windowManager.setMovable(true);` but it doesn't seem to work.

**Comment by lijy91** [comment]
Fixed on https://github.com/leanflutter/window_manager/pull/482

**Comment by letrungdo** [comment]
@lijy91 new bug has arisen on Windows OS
When set titleBarStyle: TitleBarStyle.hidden and toggle maximize window
Then go to settings and adjust the Display scale to 150%, then adjust the scale to 100%
=> scale 100% it scales larger than 150% => NG
