### ISSUE TITLE
[Windows] Maximizing window on secondary monitor broken in 0.4.0

### ISSUE THREAD

**Issue by MindStudioOfficial** [leanflutter/window_manager#485]
I have 4 monitors each with different resolutions and scalings.

Since 0.4.0 maximizing the window on the monitors that are not the main monitor causes the window contents to freeze and don't scale correctly.
Rolling back to 0.3.9 and running `flutter clean` fixes the issue indicating that commit fa2a96308c80b11f70ad54f1d1fe74148f143c47 introduced the issue.

I am on Flutter stable 3.24.0 with dart 3.5.0

possibly related to #483

**Comment by lijy91** [comment]
Fixed on https://github.com/leanflutter/window_manager/pull/482
