### ISSUE TITLE
[Bug] [Windows] [0.4.2] Window contents sized wrongly after restore from minimized

### ISSUE THREAD

**Issue by MindStudioOfficial** [leanflutter/window_manager#489]
When minimizing the window and restoring it after it was maximized the contents of the window are scaled wrongly.

This only happens when the window was previously maximized when minimizing.
Restoring to an unmaximized window works as expected.
Also this issue appears on all monitors regardless of resolution scaling or position.
This issue first appears in release 0.4.2.

**Comment by WinXaito** [comment]
I can confirm that.

After some tests here is the result:

- `0.3.9 => OK`
- `0.4.0 => Maximize and restore from task bar (clic to minimize and click again to restore) are broken`
- `0.4.1 => Maximize and restore from task bar (clic to minimize and click again to restore) are broken`
- `0.4.2 => Maximize is OK but, still the problem from the task bar`

So it looks like https://github.com/leanflutter/window_manager/pull/482 fix a part of the problem but not completly. So I have to stay in `0.3.9` for the moment.

**Comment by fufesou** [comment]
@MindStudioOfficial @WinXaito Hi, I'm trying to fix this issue.

Could you please give more details about how to reproduce this issue? Or could you please upload a video? Thx

**Comment by fufesou** [comment]
I've reproduced. I'll fix it.

**Comment by LambGe** [comment]
![image](https://github.com/user-attachments/assets/6b493d36-6f0b-4de5-bd7c-f5ed269b4c9f)
window_manager: 0.4.2

I have also encountered this issue.
