### ISSUE TITLE
Make package a federated plugin, so optional implemenations can be added

### ISSUE THREAD

**Issue by Gustl22** [leanflutter/window_manager#490]
I propose to convert this package to a federated plugin, so developers can add more platforms, if wanted.

I may can start with a proposal PR, if wanted.

See: https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins

Best regards.

FYI, I really would like to see web and mobile implemented, which may is to much effort to solve it all in this package.

**Comment by lijy91** [comment]
I'm working on it https://github.com/leanflutter/window_manager/pull/506

**Comment by Gustl22** [comment]
So cool, if you need help, let me know!

**Comment by Gustl22** [comment]
@lijy91 can we reopen and I may try to work on it. Using ffi is independent from making a plugin federated.
FFI is still different for each platform. So it should be called on each plugins implementation. Federation allows contributors to implement their own impletation e.g. for unsupported platforms like web.
FFI can still happen later in those packages per platform.
