### ISSUE TITLE
Issue with Page Content Disappearing After Minimize/Maximize When Using Multiple Monitors

### ISSUE THREAD

**Issue by tanvirulislam** [leanflutter/window_manager#498]
I'm using the Flutter window_manager package to hide the window title bar in my desktop app. However, I'm encountering an issue when an external monitor is connected or when the display is extended. After minimizing and then maximizing the app, the page content disappears. This only happens with an external monitor, and the issue doesn't occur when using a single monitor.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.4169], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.4)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.94.0)
[√] Connected device (4 available)
[√] Network resources
• No issues found!
[project github link](https://github.com/tanvirulislam/window_titlebar_hiding_issue)

https://github.com/user-attachments/assets/5c3f0098-4918-472b-b5f0-aa202cd55959

**Comment by WinXaito** [comment]
Seems related to #489 (with a possible fix here: #495)
