### ISSUE TITLE
[Bug] [Windows] [0.4.2] Window contents sized wrongly after restore from minimized or drag from one screen to another

### ISSUE THREAD

**Issue by LambGe** [leanflutter/window_manager#499]
This issue occurs when the window is minimized and restored, and it is a common occurrence on extended screens.

![image](https://github.com/user-attachments/assets/cc554e16-e475-4b2e-9f91-a5c52c6394e4)

window_manager: 0.4.2

**Comment by lijy91** [comment]
Please update to 0.4.3
