### ISSUE TITLE
Open once

### ISSUE THREAD

**Issue by mbfakourii** [leanflutter/window_manager#505]
It is not possible to set the program to not open a new instance of the program if it is open.

Open only one instance.

For example, if you clicked on the exe output file several times, only one instance of the program will open

**Comment by lijy91** [comment]
Did you configure the single instance according to this article? https://leanflutter.dev/tips-and-tricks/001-making-the-app-single-instanced/

**Comment by lijy91** [comment]
Please provide your code

**Comment by mbfakourii** [comment]
Thanks, solved
