### ISSUE TITLE
Add/document "Hidden at launch" mechanism for Windows

### ISSUE THREAD

**Issue by mkulesh** [leanflutter/window_manager#51]
Thank you for amazing package! I am trying to use this package for my app https://github.com/mkulesh/onpc. It seems to be working fine on macOS. However I am not able to keep the app "Hidden at launch" on Windows. How can I hide the window on Windows before new size and position is applied?

**Comment by mkulesh** [comment]
Hi! I am now able to hide windows app at launch as well and submitted a pull request that expands the documentation about it. Do you have any ideas how can I hide now the Linux app at launch?

**Comment by lijy91** [comment]
I updated the documentation and made some optimizations
