### ISSUE TITLE
idn generic flutter AntiVirus

### ISSUE THREAD

**Issue by Eerey** [leanflutter/window_manager#53]
![image](https://user-images.githubusercontent.com/7249645/149750353-0b214329-56ca-40bc-84d8-a32334df3403.png)
After launching, this happened.
Is this related to this plugin?

**Comment by damywise** [comment]
https://whatt.org/questions/tech/what-is-idp-generic/
this might help

**Comment by lijy91** [comment]
May be because the app is not signed
