### ISSUE TITLE
使用过程中遇到几个问题

### ISSUE THREAD

**Issue by wuyugege** [leanflutter/window_manager#58]
1、如果采用无边框模式，调用最大化方法后，产生的效果是全屏，底部任务栏不显示
2、最大化后，窗口顶部会少显示几个像素，造成窗口不能完全显示
3、采用无边框模式，启动后窗口顶部会有2个像素的白条，非必现

**Comment by fefz** [comment]
setMinimumSize() 不起作用，还是可以手动调整窗口位置到很小。

**Comment by lijy91** [comment]
Fixed, will be released in next version
