### ISSUE TITLE
abbility to center window on current screen

### ISSUE THREAD

**Issue by sleepreading** [leanflutter/window_manager#59]
Win32 has this feature, just call `CenterWindow()`.
Hope to add this feature in the future.

**Comment by darkstarx** [comment]
Also it would be great if the plugin had function `getScreenRect`. It could bring us the more flexibility to align our window relatively the screen (not only center but also set to `topLeft` or `bottomRight`, you know).
You can take the code from this plugin https://github.com/bitsdojo/bitsdojo_window (see `appWindow.alignment = Alignment.center;`)

**Comment by lijy91** [comment]
Please upgrade to `v0.1.5`
