### ISSUE TITLE
Add support for android

### ISSUE THREAD

**Issue by bdlukaa** [leanflutter/window_manager#62]
Currently, we can run Android apps on Windows using Chrome Book or Samsung Dex. It'd be awesome if we could have customization methods for these as well. I know most features won't be supported, but the most basic ones could be!

Useful links:

- <https://developer.android.com/topic/arc/window-management>
- <https://chromeos.dev/en/android/window-management>
- <https://developer.android.com/guide/topics/large-screens/multi-window-support>

**Comment by lijy91** [comment]
No plans to support android yet

**Comment by longfit** [comment]
I have problem debug android platform which will be paused
on exception
 Future<bool> isMaximized() async {
    return await _channel.invokeMethod('isMaximized');
  }

how to avoid when i switch the android platform

**Comment by bdlukaa** [comment]
don't call it on the android platform:

```dart
if (!Platform.isAndroid && !Platform.isIOS) ...
```
