### ISSUE TITLE
[Windows] Removing WS_CAPTION (titleBarStyle = 'hidden') Disables Animation

### ISSUE THREAD

**Issue by damywise** [leanflutter/window_manager#64]
No animation during maximize, minimize, close, etc.
Need to find a workaround or another method to remove title bar while still enabling border and resize and retaining animation (like chromium, electron, etc)

**Comment by lijy91** [comment]
Any clues? I haven't been able to find another way.

**Comment by damywise** [comment]
Finally found [this](https://github.com/melak47/BorderlessWindow) a few minutes ago.
I've confirmed that it works on my machine (windows 10 using vs 2022). I don't know how to implement it here though.
Hope this helps a little.

**Comment by lijy91** [comment]
I know this too, I tried to integrate it, but it didn't work.

**Comment by damywise** [comment]
I've succeeded enabling animation in titleBarStyle 'hidden'.
The code needs some tweaking so that isMinimizable and isClosable would work probably.
I'll share the code tomorrow since I'm tired right now and need to go to sleep.

**Comment by damywise** [comment]
Oh yea I didn't mention that the top resize border won't work anymore.

**Comment by damywise** [comment]
There's also this
https://github.com/rossy/borderless-window

**Comment by lijy91** [comment]
Fixed, will be released in next version
