### ISSUE TITLE
When using "setTitleBarStyle('hidden')" and "maximize()" on windows the app maximize to full screen hiding the taskbar

### ISSUE THREAD

**Issue by nabileisa** [leanflutter/window_manager#65]
When using `windowManager.setTitleBarStyle('hidden')` or  `windowManager.setAsFrameless()` with `windowManager.maximize()` to maximize the window on windows the app maximize to full screen hiding the taskbar.
Is this a bug, or is this the expected behavior?
if it is the expected behavior, how do I get it to not do that and maximize above the task bar like normal apps.
thanks for the great work on this library

**Comment by lijy91** [comment]
Fixed, will be released in next version
