### ISSUE TITLE
How to "reset" the window after run setAsFrameless?

### ISSUE THREAD

**Issue by Falamarcao** [leanflutter/window_manager#68]
After setting as frameless how do we show again the title bar and buttons (close, minimize, maximize)?

setTitleBarStyle seems not to work after call setAsFrameless. I tried on sequence and on dispose method of my flutter  fake splash screen. I tried only on MacOs 12.0.1, so i don’t know about Windows OS.

`await windowManager.setTitleBarStyle('visible', windowButtonVisibility: true);`

I'm wishing  to use **setAsFrameless to mimic a splash screen** on desktop - native splash screens for desktop are not  supported by Flutter yet.

Thank you.

**Comment by lijy91** [comment]
```dart
windowManager.setTitleBarStyle(TitleBarStyle.normal);
```
