### ISSUE TITLE
请问为什么无法初始化导入？

### ISSUE THREAD

**Issue by milukun** [leanflutter/window_manager#7]
flutter 2.5.2
![image](https://user-images.githubusercontent.com/73962678/135824694-24802119-af7e-4c94-ac18-00ebf2ee09e2.png)

**Comment by milukun** [comment]
搞定了，好像是pub.dev上的版本有问题。对比了源码，pub上直接拉的确实没有这个方法

**Comment by milukun** [comment]
1.

**Comment by lijy91** [comment]
以 pub 为准 master 有未发布的api
