### ISSUE TITLE
[windows] Horizontal resizing not working on secondary display.

### ISSUE THREAD

**Issue by ZyphenVisuals** [leanflutter/window_manager#71]
Original issue on the Flutter repo: Flutter/Flutter#98353 

Quick recap:
After installing `window_manager` into a project, even without importing it or using it in any way, the app refuses to resize horizontally on a secondary display. 

Video demonstration: https://www.youtube.com/watch?v=R2KcCFDJOUs&feature=youtu.be

**Comment by damywise** [comment]
Can you try using each version of window_manager and see if one of them works?

**Comment by ZyphenVisuals** [comment]
It works correctly on 0.1.3. Any version newer has the error.

Hope this helps!

**Comment by damywise** [comment]
Can you try using this package and see if it works now?
[window_manager-0.1.5-test.zip](https://github.com/leanflutter/window_manager/files/8069056/window_manager-0.1.5-test.zip)

**Comment by ZyphenVisuals** [comment]
Tested, work correctly on my end. Will this fix be published in 0.1.6?

**Comment by damywise** [comment]
Well that depends. I should make the PR first tho

**Comment by lijy91** [comment]
PR merged, will be released in next version.
