### ISSUE TITLE
[Windows] Double Clicking DragToResizeArea should Simulate Vertical Aero Snap

### ISSUE THREAD

**Issue by damywise** [leanflutter/window_manager#77]
Double clicking the top and bottom part of  DragToResizeArea widget doesn't do anything when it should've maximized the window vertically and could be restored to the original size.
According to this
https://stackoverflow.com/questions/34230743/how-to-vertically-resize-a-window-in-code
SetWindowPlacement is the way to do it

**Comment by rmill777** [comment]
`GestureDetector(
                    child: Container(
                      width: 50,
                      height: 50,
                      color: Colors.purple,
                    ),
                    onTapDown: (_) {
                      windowManager.startDragging();
                    },
                    onDoubleTap: () async {
                      bool isMaximized = await windowManager.isMaximized();
                      if (isMaximized) {
                        windowManager.restore();
                      } else {
                        windowManager.maximize();
                      }
                    },
                  ),`
