### ISSUE TITLE
Feature request: Remember last window position

### ISSUE THREAD

**Issue by damywise** [leanflutter/window_manager#78]
For example:
setRememberLastPosition(true);
Makes it so the app stays on that position when closed and reopened
[might be related](https://stackoverflow.com/questions/20624720/how-to-set-in-win32-program-to-enable-size-being-remembered)

**Comment by damywise** [comment]
Or maybe just use shared_preferences to save and load position during start / close

**Comment by lijy91** [comment]
I think the user can do this by hidden at launch.
