### ISSUE TITLE
Visual bug in fullscreen

### ISSUE THREAD

**Issue by CodeDoctorDE** [leanflutter/window_manager#83]
I'm using this button to control the fullscreen
```dart
IconButton(
                  icon: const Icon(PhosphorIcons.frameCornersLight),
                  iconSize: 16,
                  splashRadius: 20,
                  onPressed: () async {
                    var current = await windowManager.isFullScreen();
                    await windowManager.setFullScreen(!current);
                  },
                ),
```

If I click on it, it looks like this
![image](https://user-images.githubusercontent.com/20452814/156247389-2afd9a9e-e850-43a4-bb0f-893553fbe7ea.png)
The appbar seems to be replicated.

If you want to test it on the my app: https://github.com/LinwoodCloud/Butterfly/tree/CodeDoctorDE/issue117/app

**Comment by damywise** [comment]
Correction: It's not the appbar but the whole app (top, bottom, and the sides). I think this might be caused by the app border not removed properly.

**Comment by lijy91** [comment]
Can you try running window_manager example app.

**Comment by lijy91** [comment]
I thought of a way, set titlebar style to default before entering full screen.

**Comment by lijy91** [comment]
Please update to `v0.1.9`
