### ISSUE TITLE
Render on Win7 and Win8.1 is not good

### ISSUE THREAD

**Issue by WinXaito** [leanflutter/window_manager#84]
I know Windows 7 is not longer supported. But I'm putting this off for your information. I don't necessarily expect a fix.

Windows 8.1 is better, but not good as well.

![window_manager_w7](https://user-images.githubusercontent.com/8223773/156719577-bb0f30d0-7058-4b15-86e3-b07467c82674.gif)

**Comment by lijy91** [comment]
I have no plans to support win7 and win 8

**Comment by kevinxxq** [comment]
Hi,
Do you have any idea for this? or the other way, do you think it will work just turning off the frameless feature?
Thank you.
