### ISSUE TITLE
[Feature Request] onChangeTheme method

### ISSUE THREAD

**Issue by YehudaKremer** [leanflutter/window_manager#86]
Hello, thank you for this useful package.

Is it possible to add an event method that fire when the windows theme is changed:
1. dark mode activated/turn off
2. color theme changed

Anyway, thanks again! 👍

**Comment by lijy91** [comment]
I added the setBrightness method, which can toggle between light/dark mode.

https://user-images.githubusercontent.com/3889523/156914825-7c1e7ed3-7bb1-42a5-84fc-45c1a89d1fd5.mp4

**Comment by YehudaKremer** [comment]
Thanks for the super quick response and the nice toggle function (i will use it) 👍 

But I meant that when the user goes to windows settings and manually change the system theme mode or theme color,
then the function `onChangeTheme` will fire up so my app will know that is time to use: `await SystemTheme.accentInstance.load();`

Sorry if I was not clear enough :sweat:

**Comment by lijy91** [comment]
The flutter engine supports monitoring theme changes, you just need to call setBrightness there.

https://stackoverflow.com/a/62607827

**Comment by lijy91** [comment]
https://user-images.githubusercontent.com/3889523/156916556-bd1fe9b8-0f00-40c8-8a68-a431394d411c.mp4

**Comment by lijy91** [comment]
Supported, will be released in the next version

**Comment by YehudaKremer** [comment]
Thank you! I didn't know that.

Theme Mode change detection, worked only after I added what you quote:
> Currently in windows this must be added https://github.com/flutter/flutter/pull/88520/files

Very cool!

The only extra thing that I don't know if it's covered by Flutter for windows,
is the change detection of theme **color** (not the theme **mode**),

Do you know anything about that?
![Video-detail-page](https://user-images.githubusercontent.com/946652/156918169-398eefe0-61ed-4f7f-91fe-1c6257df12ee.gif)

**Comment by lijy91** [comment]
Unfortunately, it cannot detect custom themes

**Comment by YehudaKremer** [comment]
I guess it's early days for flutter-windows...

Thanks again for your help (https://github.com/leanflutter/window_manager/commit/6eb721cacf4d7c5b6c700afac6279ff7043644b9) and knowledge share (https://github.com/leanflutter/window_manager/issues/86#issuecomment-1059920641) 👍

**Comment by lijy91** [comment]
By the way, you can use [system_theme](https://github.com/bdlukaa/system_theme) to get the system accent color.

**Comment by YehudaKremer** [comment]
Already using it, works well 👍
