### ISSUE TITLE
hide task bar

### ISSUE THREAD

**Issue by tamirlet** [leanflutter/window_manager#88]
hi, can I hide windows/macos task bar and setting bar and apply full screen mode to all the screen , I dont want to see anything else but the app? how can I do it if it's possible?

**Comment by lijy91** [comment]
You can call `setSkipTaskbar` method to hide it.  It supports `Linux`, `macOS` and `Windows`.

https://github.com/leanflutter/window_manager#setskiptaskbar

**Comment by tamirlet** [comment]
i want to hide the toolbar, not the application from the toolbar. when i do this line it only disappearing the icon from the dock

**Comment by lijy91** [comment]
I'm sorry I misunderstood, but it shouldn't be handle by window_manager.

**Comment by FrankDiao** [comment]
> 我想隐藏工具栏，而不是工具栏中的应用程序。当我执行此操作时，它只会从停止靠栏中消失图标

HI.
Do you have a solution yet? I also have the same requirement currently (pop up the app window from the bottom of the desktop and place it at the bottom of the desktop).
