### ISSUE TITLE
[Feature Request]: Add ignoring mouse events 

### ISSUE THREAD

**Issue by bdorlov** [leanflutter/window_manager#89]
Hello, thanks for this excellent plugin.
Could you please add an implementation of passing mouse events through the app window?
Something, like this 
https://www.electronjs.org/docs/latest/api/browser-window#winsetignoremouseeventsignore-options
Related links with the same problem:
https://stackoverflow.com/questions/66454744/flutter-desktop-ignore-mouse-events
https://stackoverflow.com/questions/71096699/letting-the-mouse-pass-through-windows-flutter

**Comment by lijy91** [comment]
I have added `setIgnoreMouseEvents` method in macos and windows platform.
