### ISSUE TITLE
Add method to activate app without showing the main window

### ISSUE THREAD

**Issue by cbenhagen** [leanflutter/window_manager#90]
Similar to `focus` but without showing the main window. On macOS this would only call `NSApp.activate(ignoringOtherApps: true)`. Our app is mostly just the menu in the system tray (using https://github.com/leanflutter/tray_manager). Therefore it would be nice to be able to activate it without showing the main window which currently is only its settings. Activating is for example needed before showing an alert window.

Maybe there could also be an optional parameter `showWindow` on the `focus` method which defaults to true?

**Comment by lijy91** [comment]
Can you call the hide method to hide the main window?

**Comment by cbenhagen** [comment]
The main window is already hidden. But using the focus method will show it.

**Comment by lijy91** [comment]
Why call focus if the window is hidden?

**Comment by lijy91** [comment]
Can you share a screenshot or video to introduce your product features?

**Comment by cbenhagen** [comment]
The app can show native alert windows which need focus. But maybe activating should be a feature of that plugin. I also opened an issue there. https://github.com/zonble/flutter_platform_alert/issues/2

**Comment by lijy91** [comment]
I solved this by modifying flutter_platform_alert, you can check out my fork, and I created a PR for flutter_platform_alert.

https://github.com/lijy91/flutter_platform_alert
https://github.com/zonble/flutter_platform_alert/pull/3

**Comment by cbenhagen** [comment]
Thanks!
