### ISSUE TITLE
Top Border Windows Can't be resize after remove title bar.

### ISSUE THREAD

**Issue by Goyp95** [leanflutter/window_manager#91]
any workaround for this issue.. right now i use window_manager plugin together with bitsdojo_window plugin, it's work but bitsdojo_window has some error, so i can't use widget inspector in vscode.

**Comment by lijy91** [comment]
Have you tried using the DragToMoveArea widget?

```dart
DragToResizeArea(
  enableResizeEdges: [
    ResizeEdge.topLeft,
    ResizeEdge.top,
    ResizeEdge.topRight,
  ],
  child: Container(),
)
```

**Comment by Goyp95** [comment]
> lijy9
Yups ,it's works.
