### ISSUE TITLE
Bug: when resizing in maximize mode, an unrecoverable bug occurs

### ISSUE THREAD

**Issue by WinXaito** [leanflutter/window_manager#92]
Just see the gif below:

![window_manager_fs](https://user-images.githubusercontent.com/8223773/157259311-32a0692d-a27a-4815-9fc3-3c42993321b4.gif)

The resize must not be visible in maximized mode.

Tested with Fluent UI demo app.

**Comment by lijy91** [comment]
This issue was fixed, disallowing window resizing when fullscreen or maximized
