### ISSUE TITLE
WindowCaption Widget Bugs/Requests - Buttons and Top Resize

### ISSUE THREAD

**Issue by damywise** [leanflutter/window_manager#93]
- Window shouldn't start drag when clicking window buttons
- There shouldn't be any delay when clicking maximize/minimize/close button
- The height of the top resize region should be 8 pixel (if top border is completely cut off)

**Comment by lijy91** [comment]
I added a new `VirtualWindowFrame` Widget to simulate the window frame and add drag to resize the window area.
