### ISSUE TITLE
key problem

### ISSUE THREAD

**Issue by hamidjalili59** [leanflutter/window_manager#97]
![key_p](https://user-images.githubusercontent.com/42936283/158232704-54a31859-ee4a-4eb0-b9ce-401f1852a35f.png)

Greeting 🌹,
thanks for useful package📦,
I have some errors when I press any keys in my keyboard

**Comment by damywise** [comment]
It's usually a problem with Flutter, not window_manager, unless it happens only if window_manager is installed. Can you provide flutter doctor -v and steps to replicate that triggers this error ?

**Comment by hamidjalili59** [comment]
![key_p](https://user-images.githubusercontent.com/42936283/158237333-2ef2f4bf-5dcf-4ac8-bd6a-5b94a58cd952.png)

I think it's wrong with the fluent-ui library

**Comment by lijy91** [comment]
Please find the solution in the flutter repo, this is not a bug caused by `windown_manager`.

https://github.com/flutter/flutter/search?p=2&q=_pressedKeys.containsKey%28event.physicalKey%29&type=issues
