### ISSUE TITLE
setTitleBarStyle argument typing

### ISSUE THREAD

**Issue by lesnitsky** [leanflutter/window_manager#99]
`setTitleBarStyle` is purely documented.
Example shows `hidden` as a valid value, however there is no quick way to know what are other valid values.
A better API design decision would be to make the argument an enum:

```dart
enum TitleBarStyle {
  hidden,
  ...
}

await windowManager.setTitleBarStyle(TitleBarStyle.hidden); // self-documenting + autocomplete
```

I can make a PR if you're willing to accept this change

**Comment by lijy91** [comment]
I should really use an enum, it should have two values normal and hidden, look forward to your pr.

```dart
enum TitleBarStyle {
  normal,
  hidden,
}
```

**Comment by lijy91** [comment]
I've done it and will release it in the next version
